/**
 * Candidate Profile Field Registry — v2 (224 fields, 18 categories)
 *
 * Rebuilt from NAH_Profile_Tab_v2_Expanded.md (2026-04-09).
 * Single source of truth for all custom fields on a contact.
 * Drives the profile UI, API validation, and Scout field access.
 *
 * Source metadata per field is tracked in the contact_profile_fields table (EAV).
 */

export type FieldCategory =
  | "identity_contact"
  | "background_demographics"
  | "personality_psychology"
  | "goals_vision"
  | "financial"
  | "franchise_fit"
  | "territory"
  | "sales_journey"
  | "validation"
  | "trainual"
  | "compliance"
  | "objections_concerns"
  | "behavioral_signals"
  | "engagement"
  | "external_research"
  | "ai_scout"
  | "predictive_scores"
  | "metadata_audit";

export type FieldDataType = "text" | "dropdown" | "number" | "date" | "boolean" | "jsonb";

export type FieldSource = "manual" | "scout" | "system" | "api";

export interface ProfileField {
  name: string;
  label: string;
  category: FieldCategory;
  dataType: FieldDataType;
  options?: string[];
  source: FieldSource;
  relevantStage: string;
  help?: string;
}

export const PROFILE_FIELDS: ProfileField[] = [
  // ═══════════════════════════════════════
  // 1. IDENTITY & CONTACT (8)
  // ═══════════════════════════════════════
  {
    name: "full_name",
    label: "Full Name",
    category: "identity_contact",
    dataType: "text",
    source: "api",
    relevantStage: "New Lead",
  },
  {
    name: "first_name",
    label: "First Name",
    category: "identity_contact",
    dataType: "text",
    source: "scout",
    relevantStage: "New Lead",
  },
  {
    name: "last_name",
    label: "Last Name",
    category: "identity_contact",
    dataType: "text",
    source: "scout",
    relevantStage: "New Lead",
  },
  {
    name: "email",
    label: "Email",
    category: "identity_contact",
    dataType: "text",
    source: "api",
    relevantStage: "New Lead",
  },
  {
    name: "phone",
    label: "Phone",
    category: "identity_contact",
    dataType: "text",
    source: "api",
    relevantStage: "New Lead",
  },
  {
    name: "location",
    label: "Location",
    category: "identity_contact",
    dataType: "text",
    source: "api",
    relevantStage: "New Lead",
    help: "City, state",
  },
  {
    name: "city",
    label: "City",
    category: "identity_contact",
    dataType: "text",
    source: "scout",
    relevantStage: "New Lead",
  },
  {
    name: "state",
    label: "State",
    category: "identity_contact",
    dataType: "text",
    source: "scout",
    relevantStage: "New Lead",
  },
  {
    name: "linkedin_url",
    label: "LinkedIn URL",
    category: "identity_contact",
    dataType: "text",
    source: "scout",
    relevantStage: "New Lead",
  },
  {
    name: "timezone",
    label: "Timezone",
    category: "identity_contact",
    dataType: "text",
    source: "api",
    relevantStage: "New Lead",
  },
  {
    name: "preferred_contact_method",
    label: "Preferred Contact Method",
    category: "identity_contact",
    dataType: "dropdown",
    options: ["Call", "Text", "Email"],
    source: "scout",
    relevantStage: "New Lead",
  },
  {
    name: "referral_lead_source",
    label: "Referral / Lead Source",
    category: "identity_contact",
    dataType: "text",
    source: "api",
    relevantStage: "New Lead",
  },
  {
    name: "LeadSource",
    label: "Lead Source Detail",
    category: "identity_contact",
    dataType: "text",
    source: "api",
    relevantStage: "New Lead",
  },

  // ═══════════════════════════════════════
  // 2. BACKGROUND & DEMOGRAPHICS (14)
  // ═══════════════════════════════════════
  {
    name: "current_occupation",
    label: "Current Occupation",
    category: "background_demographics",
    dataType: "text",
    source: "scout",
    relevantStage: "Qualified",
    help: "Job title + employer",
  },
  {
    name: "current_employer",
    label: "Current Employer",
    category: "background_demographics",
    dataType: "text",
    source: "scout",
    relevantStage: "Qualified",
  },
  {
    name: "industry",
    label: "Industry",
    category: "background_demographics",
    dataType: "text",
    source: "scout",
    relevantStage: "Qualified",
  },
  {
    name: "years_in_current_role",
    label: "Years in Current Role",
    category: "background_demographics",
    dataType: "number",
    source: "scout",
    relevantStage: "Qualified",
  },
  {
    name: "employment_status",
    label: "Employment Status",
    category: "background_demographics",
    dataType: "dropdown",
    options: ["Employed", "Self-Employed", "Retired", "Unemployed", "Unknown"],
    source: "scout",
    relevantStage: "Qualified",
  },
  {
    name: "education_level",
    label: "Education Level",
    category: "background_demographics",
    dataType: "dropdown",
    options: ["High School", "Some College", "Bachelors", "Masters", "Doctorate", "Trade/Vocational", "Other"],
    source: "scout",
    relevantStage: "Qualified",
  },
  {
    name: "marital_status",
    label: "Marital Status",
    category: "background_demographics",
    dataType: "dropdown",
    options: ["Single", "Married", "Divorced", "Widowed", "Unknown"],
    source: "scout",
    relevantStage: "Qualified",
  },
  {
    name: "number_of_dependents",
    label: "Number of Dependents",
    category: "background_demographics",
    dataType: "number",
    source: "scout",
    relevantStage: "Qualified",
  },
  {
    name: "family_situation",
    label: "Family Situation",
    category: "background_demographics",
    dataType: "text",
    source: "scout",
    relevantStage: "Qualified",
  },
  {
    name: "spouse_name",
    label: "Spouse / Partner Name",
    category: "background_demographics",
    dataType: "text",
    source: "scout",
    relevantStage: "Qualified",
  },
  {
    name: "business_partner_name",
    label: "Business Partner Name",
    category: "background_demographics",
    dataType: "text",
    source: "scout",
    relevantStage: "Qualified",
  },
  {
    name: "military_background",
    label: "Military Background",
    category: "background_demographics",
    dataType: "dropdown",
    options: ["Veteran", "Active", "None", "Unknown"],
    source: "scout",
    relevantStage: "Qualified",
  },
  {
    name: "entrepreneurial_history",
    label: "Entrepreneurial History",
    category: "background_demographics",
    dataType: "text",
    source: "scout",
    relevantStage: "Qualified",
  },
  {
    name: "prior_franchise_experience",
    label: "Prior Franchise Experience",
    category: "background_demographics",
    dataType: "dropdown",
    options: ["None", "Researched", "Owned Previously", "Currently Owns"],
    source: "scout",
    relevantStage: "Qualified",
  },
  {
    name: "prior_real_estate_investing",
    label: "Prior Real Estate Investing",
    category: "background_demographics",
    dataType: "text",
    source: "scout",
    relevantStage: "Qualified",
  },
  {
    name: "geographic_flexibility",
    label: "Geographic Flexibility",
    category: "background_demographics",
    dataType: "dropdown",
    options: ["Local Only", "Regional", "Willing to Relocate", "Unknown"],
    source: "scout",
    relevantStage: "Qualified",
  },
  {
    name: "relocation_willingness",
    label: "Relocation Willingness",
    category: "background_demographics",
    dataType: "dropdown",
    options: ["Yes", "No", "Maybe", "Unknown"],
    source: "scout",
    relevantStage: "Qualified",
  },
  {
    name: "skill_set_notes",
    label: "Skill Set Notes",
    category: "background_demographics",
    dataType: "text",
    source: "scout",
    relevantStage: "Qualified",
  },
  {
    name: "hobbies_interests",
    label: "Hobbies / Interests",
    category: "background_demographics",
    dataType: "text",
    source: "scout",
    relevantStage: "Qualified",
  },
  {
    name: "travel_constraints",
    label: "Travel Constraints",
    category: "background_demographics",
    dataType: "text",
    source: "scout",
    relevantStage: "Qualified",
  },
  {
    name: "health_considerations",
    label: "Health Considerations",
    category: "background_demographics",
    dataType: "text",
    source: "scout",
    relevantStage: "Qualified",
  },
  {
    name: "spouse_partner_employment",
    label: "Spouse / Partner Employment",
    category: "background_demographics",
    dataType: "text",
    source: "scout",
    relevantStage: "Qualified",
  },

  // ═══════════════════════════════════════
  // 3. PERSONALITY & PSYCHOLOGY (14) — Zorakle
  // ═══════════════════════════════════════
  {
    name: "disc_type",
    label: "DISC Type",
    category: "personality_psychology",
    dataType: "dropdown",
    options: ["D", "I", "S", "C", "DI", "DS", "DC", "IS", "IC", "SC"],
    source: "api",
    relevantStage: "Qualified",
  },
  {
    name: "d_score",
    label: "D Score",
    category: "personality_psychology",
    dataType: "number",
    source: "api",
    relevantStage: "Qualified",
  },
  {
    name: "i_score",
    label: "I Score",
    category: "personality_psychology",
    dataType: "number",
    source: "api",
    relevantStage: "Qualified",
  },
  {
    name: "s_score",
    label: "S Score",
    category: "personality_psychology",
    dataType: "number",
    source: "api",
    relevantStage: "Qualified",
  },
  {
    name: "c_score",
    label: "C Score",
    category: "personality_psychology",
    dataType: "number",
    source: "api",
    relevantStage: "Qualified",
  },
  {
    name: "zorakle_fit_score",
    label: "Zorakle Fit Score",
    category: "personality_psychology",
    dataType: "number",
    source: "api",
    relevantStage: "Qualified",
  },
  {
    name: "zorakle_values_type",
    label: "Zorakle Values Type",
    category: "personality_psychology",
    dataType: "dropdown",
    options: ["Achiever", "Societal", "Emulator", "Belonger", "Unknown"],
    source: "api",
    relevantStage: "Qualified",
  },
  {
    name: "zorakle_work_style",
    label: "Zorakle Work Style",
    category: "personality_psychology",
    dataType: "dropdown",
    options: ["Director", "Connector", "Thinker", "Promoter", "Unknown"],
    source: "api",
    relevantStage: "Qualified",
  },
  {
    name: "risk_tolerance",
    label: "Risk Tolerance",
    category: "personality_psychology",
    dataType: "dropdown",
    options: ["Low", "Medium", "High"],
    source: "api",
    relevantStage: "Qualified",
  },
  {
    name: "decision_making_style",
    label: "Decision-Making Style",
    category: "personality_psychology",
    dataType: "dropdown",
    options: ["Analytical", "Gut", "Consensus"],
    source: "scout",
    relevantStage: "Qualified",
  },
  {
    name: "coachability_signal",
    label: "Coachability Signal",
    category: "personality_psychology",
    dataType: "text",
    source: "scout",
    relevantStage: "Qualified",
  },
  {
    name: "communication_style",
    label: "Communication Style",
    category: "personality_psychology",
    dataType: "dropdown",
    options: ["Direct", "Expressive", "Reserved"],
    source: "scout",
    relevantStage: "Contacted",
  },
  {
    name: "stress_response",
    label: "Stress Response",
    category: "personality_psychology",
    dataType: "text",
    source: "scout",
    relevantStage: "Qualified",
  },
  {
    name: "competitive_drive",
    label: "Competitive Drive",
    category: "personality_psychology",
    dataType: "text",
    source: "scout",
    relevantStage: "Qualified",
  },
  {
    name: "values_alignment",
    label: "Values Alignment",
    category: "personality_psychology",
    dataType: "text",
    source: "scout",
    relevantStage: "Qualified",
  },
  {
    name: "closest_franchisee_match",
    label: "Closest Franchisee Match",
    category: "personality_psychology",
    dataType: "text",
    source: "scout",
    relevantStage: "Qualified",
  },

  // ═══════════════════════════════════════
  // 4. GOALS & VISION (12)
  // ═══════════════════════════════════════
  {
    name: "Why NAH",
    label: "Why NAH?",
    category: "goals_vision",
    dataType: "text",
    source: "manual",
    relevantStage: "Qualified",
  },
  {
    name: "Primary Goal",
    label: "Primary Goal",
    category: "goals_vision",
    dataType: "dropdown",
    options: ["Full-time business", "Side income", "Portfolio diversification", "Career change", "Legacy building"],
    source: "manual",
    relevantStage: "Qualified",
  },
  {
    name: "Motivation Clarity",
    label: "Motivation",
    category: "goals_vision",
    dataType: "dropdown",
    options: ["Strong", "Moderate", "Weak"],
    source: "manual",
    relevantStage: "Qualified",
  },
  {
    name: "definition_of_success",
    label: "Definition of Success",
    category: "goals_vision",
    dataType: "text",
    source: "scout",
    relevantStage: "Discovery",
  },
  {
    name: "timeline_intent",
    label: "Timeline Intent",
    category: "goals_vision",
    dataType: "text",
    source: "scout",
    relevantStage: "Discovery",
  },
  {
    name: "decision_timeline",
    label: "Decision Timeline",
    category: "goals_vision",
    dataType: "text",
    source: "scout",
    relevantStage: "Discovery",
  },
  {
    name: "income_goal_year_1",
    label: "Income Goal — Year 1",
    category: "goals_vision",
    dataType: "text",
    source: "scout",
    relevantStage: "Discovery",
  },
  {
    name: "income_goal_year_5",
    label: "Income Goal — Year 5",
    category: "goals_vision",
    dataType: "text",
    source: "scout",
    relevantStage: "Discovery",
  },
  {
    name: "target_houses_per_month",
    label: "Target Houses per Month",
    category: "goals_vision",
    dataType: "number",
    source: "scout",
    relevantStage: "Discovery",
  },
  {
    name: "full_time_vs_part_time",
    label: "Full-Time vs Part-Time",
    category: "goals_vision",
    dataType: "dropdown",
    options: ["Full-Time", "Part-Time", "Transitioning", "Unknown"],
    source: "scout",
    relevantStage: "Discovery",
  },
  {
    name: "growth_ambition",
    label: "Growth Ambition",
    category: "goals_vision",
    dataType: "dropdown",
    options: ["Aggressive", "Moderate", "Conservative", "Unknown"],
    source: "scout",
    relevantStage: "Discovery",
  },
  {
    name: "exit_strategy",
    label: "Exit Strategy",
    category: "goals_vision",
    dataType: "text",
    source: "scout",
    relevantStage: "Discovery",
  },
  {
    name: "other_franchises_considered",
    label: "Other Franchises Considered",
    category: "goals_vision",
    dataType: "text",
    source: "scout",
    relevantStage: "Qualified",
  },
  {
    name: "research_depth_goals",
    label: "Research Depth",
    category: "goals_vision",
    dataType: "text",
    source: "scout",
    relevantStage: "Qualified",
  },

  // ═══════════════════════════════════════
  // 5. FINANCIAL PROFILE (18) — expanded from 5
  // ═══════════════════════════════════════
  {
    name: "Capital Availability",
    label: "Capital Status",
    category: "financial",
    dataType: "dropdown",
    options: ["Confirmed", "Needs Verification", "Unknown"],
    source: "manual",
    relevantStage: "Qualified",
  },
  {
    name: "Capital Source",
    label: "Funding Method",
    category: "financial",
    dataType: "dropdown",
    options: [
      "Cash",
      "SBA Loan",
      "ROBS (Retirement Rollover)",
      "Home Equity",
      "Partner/Investor",
      "Combination",
      "Undecided",
    ],
    source: "manual",
    relevantStage: "Qualified",
  },
  {
    name: "Investment Timeline",
    label: "Investment Timeline",
    category: "financial",
    dataType: "dropdown",
    options: ["Under 6 months", "6-12 months", "12+ months"],
    source: "manual",
    relevantStage: "Qualified",
  },
  {
    name: "Financing Pre-Qualified",
    label: "Pre-Qualified?",
    category: "financial",
    dataType: "dropdown",
    options: ["Yes", "No", "In Progress", "Not Started"],
    source: "manual",
    relevantStage: "Mark Call",
  },
  {
    name: "Financial Objection",
    label: "Financial Concern",
    category: "financial",
    dataType: "dropdown",
    options: ["Investment size", "Uncertain ROI", "Wants to compare", "Needs spouse buy-in", "Needs more info", "None"],
    source: "manual",
    relevantStage: "Qualified",
  },
  {
    name: "net_worth_estimated",
    label: "Net Worth (Estimated)",
    category: "financial",
    dataType: "text",
    source: "manual",
    relevantStage: "Qualified",
  },
  {
    name: "liquid_capital_available",
    label: "Liquid Capital Available",
    category: "financial",
    dataType: "number",
    source: "manual",
    relevantStage: "Qualified",
  },
  {
    name: "total_investable_assets",
    label: "Total Investable Assets",
    category: "financial",
    dataType: "number",
    source: "manual",
    relevantStage: "Qualified",
  },
  {
    name: "annual_household_income",
    label: "Annual Household Income",
    category: "financial",
    dataType: "text",
    source: "manual",
    relevantStage: "Qualified",
  },
  {
    name: "monthly_fixed_expenses",
    label: "Monthly Fixed Expenses",
    category: "financial",
    dataType: "number",
    source: "manual",
    relevantStage: "Qualified",
  },
  {
    name: "credit_score_range",
    label: "Credit Score Range",
    category: "financial",
    dataType: "dropdown",
    options: ["Below 620", "620-679", "680-739", "740+", "Unknown"],
    source: "manual",
    relevantStage: "Qualified",
  },
  {
    name: "real_estate_holdings",
    label: "Real Estate Holdings",
    category: "financial",
    dataType: "text",
    source: "manual",
    relevantStage: "Qualified",
  },
  {
    name: "retirement_accounts",
    label: "Retirement Accounts",
    category: "financial",
    dataType: "text",
    source: "manual",
    relevantStage: "Qualified",
  },
  {
    name: "robs_401k_rollover",
    label: "ROBS / 401k Rollover",
    category: "financial",
    dataType: "dropdown",
    options: ["Yes", "No", "Exploring", "N/A"],
    source: "scout",
    relevantStage: "Mark Call",
  },
  {
    name: "sba_loan_in_play",
    label: "SBA Loan in Play",
    category: "financial",
    dataType: "dropdown",
    options: ["Yes", "No", "Applied", "Approved", "Declined"],
    source: "scout",
    relevantStage: "Mark Call",
  },
  {
    name: "financial_advisor_involved",
    label: "Financial Advisor Involved",
    category: "financial",
    dataType: "dropdown",
    options: ["Yes", "No", "Unknown"],
    source: "scout",
    relevantStage: "Qualified",
  },
  {
    name: "pfs_submitted",
    label: "PFS Submitted",
    category: "financial",
    dataType: "boolean",
    source: "api",
    relevantStage: "Compliance",
  },
  {
    name: "capital_risk_score_financial",
    label: "Capital Risk Score",
    category: "financial",
    dataType: "number",
    source: "scout",
    relevantStage: "Qualified",
  },

  // ═══════════════════════════════════════
  // 6. FRANCHISE FIT (10) — expanded from 7
  // ═══════════════════════════════════════
  {
    name: "RE Experience",
    label: "Real Estate Experience",
    category: "franchise_fit",
    dataType: "dropdown",
    options: ["None", "Some (1-3 flips)", "Experienced (4-10)", "Expert (10+)"],
    source: "manual",
    relevantStage: "Qualified",
  },
  {
    name: "Construction Knowledge",
    label: "Construction Knowledge",
    category: "franchise_fit",
    dataType: "dropdown",
    options: ["None", "Basic", "Intermediate", "Advanced"],
    source: "manual",
    relevantStage: "Qualified",
  },
  {
    name: "Business Ownership Experience",
    label: "Business Owner?",
    category: "franchise_fit",
    dataType: "dropdown",
    options: ["Yes", "No"],
    source: "manual",
    relevantStage: "Qualified",
  },
  {
    name: "Timeline to Open",
    label: "Timeline to Open",
    category: "franchise_fit",
    dataType: "dropdown",
    options: ["Immediately", "1-3 months", "3-6 months", "6-12 months", "12+ months"],
    source: "manual",
    relevantStage: "Qualified",
  },
  {
    name: "crew_management_experience",
    label: "Crew Management Experience",
    category: "franchise_fit",
    dataType: "text",
    source: "scout",
    relevantStage: "Discovery",
  },
  {
    name: "contractor_network",
    label: "Contractor Network",
    category: "franchise_fit",
    dataType: "text",
    source: "scout",
    relevantStage: "Discovery",
  },
  {
    name: "operational_readiness",
    label: "Operational Readiness",
    category: "franchise_fit",
    dataType: "text",
    source: "scout",
    relevantStage: "Discovery",
  },
  {
    name: "availability_time",
    label: "Availability (Time)",
    category: "franchise_fit",
    dataType: "text",
    source: "scout",
    relevantStage: "Discovery",
  },
  {
    name: "partnership_plans",
    label: "Partnership Plans",
    category: "franchise_fit",
    dataType: "dropdown",
    options: ["Yes", "No", "Maybe", "Unknown"],
    source: "scout",
    relevantStage: "Discovery",
  },
  {
    name: "franchise_fit_score",
    label: "Franchise Fit Score",
    category: "franchise_fit",
    dataType: "number",
    source: "scout",
    relevantStage: "Discovery",
  },

  // ═══════════════════════════════════════
  // 7. TERRITORY (10) — expanded from 4
  // ═══════════════════════════════════════
  {
    name: "Territory Interest",
    label: "Desired Territory",
    category: "territory",
    dataType: "text",
    source: "manual",
    relevantStage: "New Lead",
  },
  {
    name: "Territory Market",
    label: "Market Area",
    category: "territory",
    dataType: "text",
    source: "manual",
    relevantStage: "Qualified",
  },
  {
    name: "Territory Status",
    label: "Territory Status",
    category: "territory",
    dataType: "dropdown",
    options: ["Available", "Waitlist", "Unavailable", "Confirmed"],
    source: "manual",
    relevantStage: "Qualified",
  },
  {
    name: "Territory Confirmed Date",
    label: "Confirmed Date",
    category: "territory",
    dataType: "date",
    source: "system",
    relevantStage: "Awarding",
  },
  {
    name: "secondary_territory_preference",
    label: "Secondary Territory Preference",
    category: "territory",
    dataType: "text",
    source: "manual",
    relevantStage: "Qualified",
  },
  {
    name: "territory_value_estimate",
    label: "Territory Value Estimate",
    category: "territory",
    dataType: "text",
    source: "manual",
    relevantStage: "Qualified",
  },
  {
    name: "zip_codes_of_interest",
    label: "Zip Codes of Interest",
    category: "territory",
    dataType: "text",
    source: "manual",
    relevantStage: "Qualified",
  },
  {
    name: "local_market_conditions",
    label: "Local Market Conditions",
    category: "territory",
    dataType: "text",
    source: "scout",
    relevantStage: "Qualified",
  },
  {
    name: "territory_type_preference",
    label: "Territory Type Preference",
    category: "territory",
    dataType: "text",
    source: "scout",
    relevantStage: "Qualified",
  },
  {
    name: "competitor_presence",
    label: "Competitor Presence",
    category: "territory",
    dataType: "text",
    source: "scout",
    relevantStage: "Qualified",
  },
  {
    name: "housing_market_activity",
    label: "Housing Market Activity",
    category: "territory",
    dataType: "text",
    source: "scout",
    relevantStage: "Qualified",
  },

  // ═══════════════════════════════════════
  // 8. SALES JOURNEY (12) — milestone dates
  // ═══════════════════════════════════════
  {
    name: "first_contact_date",
    label: "First Contact Date",
    category: "sales_journey",
    dataType: "date",
    source: "api",
    relevantStage: "New Lead",
  },
  {
    name: "intro_call_date",
    label: "Intro Call Date",
    category: "sales_journey",
    dataType: "date",
    source: "api",
    relevantStage: "Engagement",
  },
  {
    name: "nda_signed_date",
    label: "NDA Signed Date",
    category: "sales_journey",
    dataType: "date",
    source: "api",
    relevantStage: "Qualified",
  },
  {
    name: "matt_call_date",
    label: "Matt Call Date",
    category: "sales_journey",
    dataType: "date",
    source: "api",
    relevantStage: "Discovery",
  },
  {
    name: "zorakle_sent_date",
    label: "Zorakle Sent Date",
    category: "sales_journey",
    dataType: "date",
    source: "api",
    relevantStage: "Discovery",
  },
  {
    name: "zorakle_completed_date",
    label: "Zorakle Completed Date",
    category: "sales_journey",
    dataType: "date",
    source: "api",
    relevantStage: "Discovery",
  },
  {
    name: "sam_call_date",
    label: "Sam Call Date",
    category: "sales_journey",
    dataType: "date",
    source: "api",
    relevantStage: "Validation",
  },
  {
    name: "mark_call_date",
    label: "Mark Call Date",
    category: "sales_journey",
    dataType: "date",
    source: "api",
    relevantStage: "Mark Call",
  },
  {
    name: "fdd_sent_date",
    label: "FDD Sent Date",
    category: "sales_journey",
    dataType: "date",
    source: "api",
    relevantStage: "Compliance",
  },
  {
    name: "fdd_item_23_signed",
    label: "FDD Item 23 Signed",
    category: "sales_journey",
    dataType: "date",
    source: "api",
    relevantStage: "Compliance",
  },
  {
    name: "territory_call_date",
    label: "Territory Call Date",
    category: "sales_journey",
    dataType: "date",
    source: "api",
    relevantStage: "Awarding",
  },
  {
    name: "matt_final_call_date",
    label: "Matt Final Call Date",
    category: "sales_journey",
    dataType: "date",
    source: "api",
    relevantStage: "Awarding",
  },

  // ═══════════════════════════════════════
  // 9. VALIDATION (8) — expanded from 6
  // ═══════════════════════════════════════
  {
    name: "Matt Call Done",
    label: "Matt Call",
    category: "validation",
    dataType: "dropdown",
    options: ["Yes - Fit Confirmed", "Yes - Concerns Flagged", "No - Not Scheduled", "No - No Show"],
    source: "manual",
    relevantStage: "Discovery",
  },
  {
    name: "Sam Call Done",
    label: "Sam Call",
    category: "validation",
    dataType: "dropdown",
    options: ["Yes - Positive", "Yes - Concerns", "No - Not Scheduled", "No - No Show"],
    source: "manual",
    relevantStage: "Validation",
  },
  {
    name: "Mark Call Done",
    label: "Mark Call",
    category: "validation",
    dataType: "dropdown",
    options: ["Yes - Financially Viable", "Yes - Needs More Info", "No - Not Scheduled", "No - No Show"],
    source: "manual",
    relevantStage: "Mark Call",
  },
  {
    name: "Franchisee Validator Name",
    label: "Validator",
    category: "validation",
    dataType: "text",
    source: "manual",
    relevantStage: "Validation",
  },
  {
    name: "NDA Status",
    label: "NDA",
    category: "validation",
    dataType: "dropdown",
    options: ["Not Sent", "Sent", "Signed"],
    source: "manual",
    relevantStage: "Qualified",
  },
  {
    name: "Discovery Scorecard Score",
    label: "Discovery Score",
    category: "validation",
    dataType: "number",
    source: "scout",
    relevantStage: "Discovery",
  },
  {
    name: "validation_call_notes",
    label: "Validation Call Notes",
    category: "validation",
    dataType: "text",
    source: "scout",
    relevantStage: "Validation",
  },
  {
    name: "capital_call_notes",
    label: "Capital Call Notes",
    category: "validation",
    dataType: "text",
    source: "scout",
    relevantStage: "Mark Call",
  },

  // ═══════════════════════════════════════
  // 10. TRAINUAL (5)
  // ═══════════════════════════════════════
  {
    name: "Framing Call Logged",
    label: "Framing Call Done?",
    category: "trainual",
    dataType: "dropdown",
    options: ["Yes", "No"],
    source: "manual",
    relevantStage: "Contacted",
  },
  {
    name: "Trainual Access Sent",
    label: "Access Sent?",
    category: "trainual",
    dataType: "dropdown",
    options: ["Yes", "No"],
    source: "system",
    relevantStage: "New Lead",
  },
  {
    name: "Trainual Completion Percent",
    label: "Completion %",
    category: "trainual",
    dataType: "number",
    source: "api",
    relevantStage: "New Lead",
  },
  {
    name: "Trainual Last Opened Date",
    label: "Last Opened",
    category: "trainual",
    dataType: "date",
    source: "api",
    relevantStage: "New Lead",
  },
  {
    name: "Trainual Current Section",
    label: "Current Section",
    category: "trainual",
    dataType: "text",
    source: "api",
    relevantStage: "New Lead",
  },

  // ═══════════════════════════════════════
  // 11. COMPLIANCE (6) — expanded from 4
  // ═══════════════════════════════════════
  {
    name: "Spouse Aware",
    label: "Spouse Aware?",
    category: "compliance",
    dataType: "dropdown",
    options: ["Yes", "No", "N/A (Single)", "Unknown"],
    source: "manual",
    relevantStage: "Qualified",
  },
  {
    name: "OK to SMS Confirmed Date",
    label: "SMS Opt-In",
    category: "compliance",
    dataType: "date",
    source: "manual",
    relevantStage: "New Lead",
  },
  {
    name: "Earnings Claims Made",
    label: "Earnings Claims",
    category: "compliance",
    dataType: "dropdown",
    options: ["No - Confirmed Clean", "Yes - Flagged"],
    source: "manual",
    relevantStage: "Compliance",
  },
  {
    name: "Compliance Checklist Complete",
    label: "Compliance",
    category: "compliance",
    dataType: "dropdown",
    options: ["Yes", "No"],
    source: "system",
    relevantStage: "Compliance",
  },
  {
    name: "attorney_involved",
    label: "Attorney Involved",
    category: "compliance",
    dataType: "dropdown",
    options: ["Yes", "No", "Unknown"],
    source: "scout",
    relevantStage: "Compliance",
  },
  {
    name: "fdd_questions",
    label: "FDD Questions",
    category: "compliance",
    dataType: "text",
    source: "scout",
    relevantStage: "Compliance",
  },
  {
    name: "fdd_14_day_window",
    label: "FDD 14-Day Window",
    category: "compliance",
    dataType: "number",
    source: "system",
    relevantStage: "Compliance",
  },
  {
    name: "llc_name",
    label: "LLC Name",
    category: "compliance",
    dataType: "text",
    source: "manual",
    relevantStage: "Compliance",
  },

  // ═══════════════════════════════════════
  // 12. OBJECTIONS & CONCERNS (12) — AI
  // ═══════════════════════════════════════
  {
    name: "capital_objection",
    label: "Capital Objection",
    category: "objections_concerns",
    dataType: "text",
    source: "scout",
    relevantStage: "Qualified",
  },
  {
    name: "territory_objection",
    label: "Territory Objection",
    category: "objections_concerns",
    dataType: "text",
    source: "scout",
    relevantStage: "Qualified",
  },
  {
    name: "timing_objection",
    label: "Timing Objection",
    category: "objections_concerns",
    dataType: "text",
    source: "scout",
    relevantStage: "Qualified",
  },
  {
    name: "spouse_partner_resistance",
    label: "Spouse / Partner Resistance",
    category: "objections_concerns",
    dataType: "text",
    source: "scout",
    relevantStage: "Qualified",
  },
  {
    name: "risk_concern",
    label: "Risk Concern",
    category: "objections_concerns",
    dataType: "text",
    source: "scout",
    relevantStage: "Qualified",
  },
  {
    name: "competitive_alternative",
    label: "Competitive Alternative",
    category: "objections_concerns",
    dataType: "text",
    source: "scout",
    relevantStage: "Qualified",
  },
  {
    name: "competitors_mentioned",
    label: "Competitors Mentioned",
    category: "objections_concerns",
    dataType: "text",
    source: "scout",
    relevantStage: "Qualified",
  },
  {
    name: "competitor_notes",
    label: "Competitor Notes",
    category: "objections_concerns",
    dataType: "text",
    source: "scout",
    relevantStage: "Qualified",
  },
  {
    name: "objections_raised",
    label: "Objections Raised",
    category: "objections_concerns",
    dataType: "text",
    source: "scout",
    relevantStage: "Qualified",
  },
  {
    name: "prior_franchise_research",
    label: "Prior Franchise Research",
    category: "objections_concerns",
    dataType: "text",
    source: "scout",
    relevantStage: "Qualified",
  },
  {
    name: "skepticism_signal",
    label: "Skepticism Signal",
    category: "objections_concerns",
    dataType: "text",
    source: "scout",
    relevantStage: "Qualified",
  },
  {
    name: "key_sticking_point",
    label: "Key Sticking Point",
    category: "objections_concerns",
    dataType: "text",
    source: "scout",
    relevantStage: "Qualified",
  },
  {
    name: "objection_count",
    label: "Objection Count",
    category: "objections_concerns",
    dataType: "number",
    source: "scout",
    relevantStage: "All",
  },
  {
    name: "unresolved_objections",
    label: "Unresolved Objections",
    category: "objections_concerns",
    dataType: "number",
    source: "scout",
    relevantStage: "All",
  },
  {
    name: "objection_trend",
    label: "Objection Trend",
    category: "objections_concerns",
    dataType: "dropdown",
    options: ["Improving", "Worsening", "Stable"],
    source: "scout",
    relevantStage: "All",
  },
  {
    name: "last_objection_date",
    label: "Last Objection Date",
    category: "objections_concerns",
    dataType: "date",
    source: "scout",
    relevantStage: "All",
  },

  // ═══════════════════════════════════════
  // 13. BEHAVIORAL SIGNALS (12)
  // ═══════════════════════════════════════
  {
    name: "engagement_level",
    label: "Engagement Level",
    category: "behavioral_signals",
    dataType: "number",
    source: "scout",
    relevantStage: "All",
  },
  {
    name: "average_response_time",
    label: "Average Response Time",
    category: "behavioral_signals",
    dataType: "text",
    source: "api",
    relevantStage: "All",
  },
  {
    name: "meeting_punctuality",
    label: "Meeting Punctuality",
    category: "behavioral_signals",
    dataType: "dropdown",
    options: ["On Time", "Late", "No-Show Pattern"],
    source: "scout",
    relevantStage: "All",
  },
  {
    name: "question_quality",
    label: "Question Quality",
    category: "behavioral_signals",
    dataType: "dropdown",
    options: ["Thoughtful", "Surface", "Minimal", "None"],
    source: "scout",
    relevantStage: "All",
  },
  {
    name: "research_depth_behavioral",
    label: "Research Depth",
    category: "behavioral_signals",
    dataType: "text",
    source: "scout",
    relevantStage: "All",
  },
  {
    name: "enthusiasm_level",
    label: "Enthusiasm Level",
    category: "behavioral_signals",
    dataType: "dropdown",
    options: ["High", "Medium", "Low"],
    source: "scout",
    relevantStage: "All",
  },
  {
    name: "commitment_signals",
    label: "Commitment Signals",
    category: "behavioral_signals",
    dataType: "text",
    source: "scout",
    relevantStage: "All",
  },
  {
    name: "ghost_risk",
    label: "Ghost Risk",
    category: "behavioral_signals",
    dataType: "number",
    source: "scout",
    relevantStage: "All",
  },
  {
    name: "information_consistency",
    label: "Information Consistency",
    category: "behavioral_signals",
    dataType: "text",
    source: "scout",
    relevantStage: "All",
  },
  {
    name: "decision_readiness",
    label: "Decision Readiness",
    category: "behavioral_signals",
    dataType: "text",
    source: "scout",
    relevantStage: "All",
  },
  {
    name: "influencer_identified",
    label: "Influencer Identified",
    category: "behavioral_signals",
    dataType: "text",
    source: "scout",
    relevantStage: "All",
  },
  {
    name: "no_show_count",
    label: "No-Show Count",
    category: "behavioral_signals",
    dataType: "number",
    source: "api",
    relevantStage: "All",
  },

  // ═══════════════════════════════════════
  // 14. ENGAGEMENT (8) — expanded from 6
  // ═══════════════════════════════════════
  {
    name: "Sequence Day Number",
    label: "Sequence Day",
    category: "engagement",
    dataType: "number",
    source: "system",
    relevantStage: "New Lead",
  },
  {
    name: "Sequence Status",
    label: "Sequence",
    category: "engagement",
    dataType: "dropdown",
    options: ["Active", "Paused", "Completed", "Exited Early"],
    source: "system",
    relevantStage: "New Lead",
  },
  {
    name: "Last Touch Date",
    label: "Last Touch",
    category: "engagement",
    dataType: "date",
    source: "system",
    relevantStage: "All",
  },
  {
    name: "Last Touch Channel",
    label: "Last Channel",
    category: "engagement",
    dataType: "dropdown",
    options: ["Call", "SMS", "Email", "Trainual", "In-Person"],
    source: "system",
    relevantStage: "All",
  },
  {
    name: "Contact Attempt Count",
    label: "Attempts",
    category: "engagement",
    dataType: "number",
    source: "system",
    relevantStage: "Contacted",
  },
  {
    name: "Days in Current Stage",
    label: "Days in Stage",
    category: "engagement",
    dataType: "number",
    source: "system",
    relevantStage: "All",
  },
  {
    name: "total_interactions",
    label: "Total Interactions",
    category: "engagement",
    dataType: "number",
    source: "api",
    relevantStage: "All",
  },
  {
    name: "last_meaningful_interaction",
    label: "Last Meaningful Interaction",
    category: "engagement",
    dataType: "date",
    source: "api",
    relevantStage: "All",
  },

  // ═══════════════════════════════════════
  // 15. EXTERNAL RESEARCH (10)
  // ═══════════════════════════════════════
  {
    name: "linkedin_summary",
    label: "LinkedIn Summary",
    category: "external_research",
    dataType: "text",
    source: "scout",
    relevantStage: "New Lead",
  },
  {
    name: "business_ownership_public",
    label: "Business Ownership (Public)",
    category: "external_research",
    dataType: "text",
    source: "scout",
    relevantStage: "Qualified",
  },
  {
    name: "estimated_net_worth_public",
    label: "Estimated Net Worth (Public)",
    category: "external_research",
    dataType: "text",
    source: "scout",
    relevantStage: "Qualified",
  },
  {
    name: "social_media_presence",
    label: "Social Media Presence",
    category: "external_research",
    dataType: "text",
    source: "scout",
    relevantStage: "New Lead",
  },
  {
    name: "news_mentions",
    label: "News Mentions",
    category: "external_research",
    dataType: "text",
    source: "scout",
    relevantStage: "Qualified",
  },
  {
    name: "industry_reputation",
    label: "Industry Reputation",
    category: "external_research",
    dataType: "text",
    source: "scout",
    relevantStage: "Qualified",
  },
  {
    name: "legal_financial_flags",
    label: "Legal / Financial Flags",
    category: "external_research",
    dataType: "text",
    source: "scout",
    relevantStage: "Compliance",
  },
  {
    name: "related_affiliations",
    label: "Related Affiliations",
    category: "external_research",
    dataType: "text",
    source: "scout",
    relevantStage: "Qualified",
  },
  {
    name: "market_conditions_target_area",
    label: "Market Conditions (Target Area)",
    category: "external_research",
    dataType: "text",
    source: "scout",
    relevantStage: "Qualified",
  },
  {
    name: "external_risk_flags",
    label: "External Risk Flags",
    category: "external_research",
    dataType: "text",
    source: "scout",
    relevantStage: "All",
  },

  // ═══════════════════════════════════════
  // 16. AI SCOUT INTELLIGENCE (16) — expanded from 9
  // ═══════════════════════════════════════
  {
    name: "Scout Lead Score",
    label: "Lead Score",
    category: "ai_scout",
    dataType: "number",
    source: "scout",
    relevantStage: "New Lead",
  },
  {
    name: "Scout Prospect Score",
    label: "Eclipse Score",
    category: "ai_scout",
    dataType: "number",
    source: "api",
    relevantStage: "Qualified",
  },
  {
    name: "Score Breakdown",
    label: "Score Detail",
    category: "ai_scout",
    dataType: "text",
    source: "scout",
    relevantStage: "New Lead",
  },
  {
    name: "Engagement Velocity",
    label: "Velocity",
    category: "ai_scout",
    dataType: "dropdown",
    options: ["Accelerating", "Steady", "Slowing", "Stalled"],
    source: "scout",
    relevantStage: "All",
  },
  {
    name: "Sentiment Trend",
    label: "Sentiment",
    category: "ai_scout",
    dataType: "dropdown",
    options: ["Very Positive", "Positive", "Neutral", "Cautious", "Negative"],
    source: "scout",
    relevantStage: "All",
  },
  {
    name: "Predicted Close Probability",
    label: "Close Probability",
    category: "ai_scout",
    dataType: "number",
    source: "scout",
    relevantStage: "Qualified",
  },
  {
    name: "Recommended Next Action",
    label: "Next Action",
    category: "ai_scout",
    dataType: "text",
    source: "scout",
    relevantStage: "All",
  },
  {
    name: "Auto Summary",
    label: "AI Summary",
    category: "ai_scout",
    dataType: "text",
    source: "scout",
    relevantStage: "All",
  },
  {
    name: "Lookalike Score",
    label: "Lookalike",
    category: "ai_scout",
    dataType: "number",
    source: "scout",
    relevantStage: "New Lead",
  },
  {
    name: "Communication Style",
    label: "Comm Style",
    category: "ai_scout",
    dataType: "dropdown",
    options: ["Direct/Fast", "Analytical/Detail", "Relationship/Trust", "Cautious/Slow"],
    source: "scout",
    relevantStage: "Contacted",
  },
  {
    name: "data_completeness",
    label: "Data Completeness",
    category: "ai_scout",
    dataType: "number",
    source: "scout",
    relevantStage: "All",
  },
  {
    name: "last_analyzed",
    label: "Last Analyzed",
    category: "ai_scout",
    dataType: "date",
    source: "system",
    relevantStage: "All",
  },
  {
    name: "confidence_score",
    label: "Confidence Score",
    category: "ai_scout",
    dataType: "number",
    source: "scout",
    relevantStage: "All",
  },
  {
    name: "key_strength",
    label: "Key Strength",
    category: "ai_scout",
    dataType: "text",
    source: "scout",
    relevantStage: "All",
  },
  {
    name: "key_risk",
    label: "Key Risk",
    category: "ai_scout",
    dataType: "text",
    source: "scout",
    relevantStage: "All",
  },
  {
    name: "recommended_rep_approach",
    label: "Recommended Rep Approach",
    category: "ai_scout",
    dataType: "text",
    source: "scout",
    relevantStage: "All",
  },
  {
    name: "priority_level",
    label: "Priority Level",
    category: "ai_scout",
    dataType: "number",
    source: "scout",
    relevantStage: "All",
  },

  // ═══════════════════════════════════════
  // 17. PREDICTIVE SCORES (12)
  // ═══════════════════════════════════════
  {
    name: "predicted_close_date",
    label: "Predicted Close Date",
    category: "predictive_scores",
    dataType: "date",
    source: "scout",
    relevantStage: "Qualified",
  },
  {
    name: "predicted_time_to_close",
    label: "Predicted Time to Close",
    category: "predictive_scores",
    dataType: "number",
    source: "scout",
    relevantStage: "Qualified",
  },
  {
    name: "long_term_performance_score",
    label: "Long-Term Performance Score",
    category: "predictive_scores",
    dataType: "number",
    source: "scout",
    relevantStage: "Awarding",
  },
  {
    name: "predicted_year_1_revenue",
    label: "Predicted Year 1 Revenue",
    category: "predictive_scores",
    dataType: "number",
    source: "scout",
    relevantStage: "Awarding",
  },
  {
    name: "predicted_year_1_units",
    label: "Predicted Year 1 Units",
    category: "predictive_scores",
    dataType: "number",
    source: "scout",
    relevantStage: "Awarding",
  },
  {
    name: "territory_fit_score",
    label: "Territory Fit Score",
    category: "predictive_scores",
    dataType: "number",
    source: "scout",
    relevantStage: "Qualified",
  },
  {
    name: "personality_fit_score",
    label: "Personality Fit Score",
    category: "predictive_scores",
    dataType: "number",
    source: "scout",
    relevantStage: "Qualified",
  },
  {
    name: "capital_risk_score_predictive",
    label: "Capital Risk Score",
    category: "predictive_scores",
    dataType: "number",
    source: "scout",
    relevantStage: "Qualified",
  },
  {
    name: "churn_risk_score",
    label: "Churn Risk Score",
    category: "predictive_scores",
    dataType: "number",
    source: "scout",
    relevantStage: "All",
  },
  {
    name: "fallout_point_prediction",
    label: "Fallout Point Prediction",
    category: "predictive_scores",
    dataType: "text",
    source: "scout",
    relevantStage: "All",
  },
  {
    name: "revenue_potential_score",
    label: "Revenue Potential Score",
    category: "predictive_scores",
    dataType: "number",
    source: "scout",
    relevantStage: "All",
  },
  {
    name: "similar_lost_deal",
    label: "Similar Lost Deal",
    category: "predictive_scores",
    dataType: "text",
    source: "scout",
    relevantStage: "All",
  },

  // ═══════════════════════════════════════
  // 18. METADATA & AUDIT (12)
  // ═══════════════════════════════════════
  {
    name: "profile_created",
    label: "Profile Created",
    category: "metadata_audit",
    dataType: "date",
    source: "api",
    relevantStage: "New Lead",
  },
  {
    name: "last_modified",
    label: "Last Modified",
    category: "metadata_audit",
    dataType: "date",
    source: "api",
    relevantStage: "All",
  },
  {
    name: "last_modified_by",
    label: "Last Modified By",
    category: "metadata_audit",
    dataType: "text",
    source: "api",
    relevantStage: "All",
  },
  {
    name: "active_pipeline",
    label: "Active Pipeline",
    category: "metadata_audit",
    dataType: "text",
    source: "system",
    relevantStage: "All",
  },
  {
    name: "current_stage",
    label: "Current Stage",
    category: "metadata_audit",
    dataType: "text",
    source: "system",
    relevantStage: "All",
  },
  {
    name: "days_in_pipeline",
    label: "Days in Pipeline",
    category: "metadata_audit",
    dataType: "number",
    source: "system",
    relevantStage: "All",
  },
  {
    name: "ghl_sync_status",
    label: "GHL Sync Status",
    category: "metadata_audit",
    dataType: "text",
    source: "api",
    relevantStage: "All",
  },
  {
    name: "fields_updated_by_ai",
    label: "Fields Updated by AI",
    category: "metadata_audit",
    dataType: "number",
    source: "system",
    relevantStage: "All",
  },
  {
    name: "fields_updated_by_api",
    label: "Fields Updated by API",
    category: "metadata_audit",
    dataType: "number",
    source: "system",
    relevantStage: "All",
  },
  {
    name: "fields_updated_manually",
    label: "Fields Updated Manually",
    category: "metadata_audit",
    dataType: "number",
    source: "system",
    relevantStage: "All",
  },
  {
    name: "data_conflicts",
    label: "Data Conflicts",
    category: "metadata_audit",
    dataType: "text",
    source: "scout",
    relevantStage: "All",
  },
  {
    name: "verification_needed",
    label: "Verification Needed",
    category: "metadata_audit",
    dataType: "text",
    source: "scout",
    relevantStage: "All",
  },
];

export const CATEGORY_META: Record<FieldCategory, { label: string; icon: string; color: string; sortOrder: number }> = {
  identity_contact: { label: "Identity & Contact", icon: "User", color: "text-info", sortOrder: 1 },
  background_demographics: { label: "Background & Demographics", icon: "Briefcase", color: "text-muted", sortOrder: 2 },
  personality_psychology: {
    label: "Personality & Psychology",
    icon: "Brain",
    color: "text-scout-purple",
    sortOrder: 3,
  },
  goals_vision: { label: "Goals & Vision", icon: "Target", color: "text-nah-orange", sortOrder: 4 },
  financial: { label: "Financial Profile", icon: "DollarSign", color: "text-success", sortOrder: 5 },
  franchise_fit: { label: "Franchise Fit", icon: "Puzzle", color: "text-nah-orange", sortOrder: 6 },
  territory: { label: "Territory", icon: "MapPin", color: "text-info", sortOrder: 7 },
  sales_journey: { label: "Sales Journey", icon: "TrendingUp", color: "text-warning", sortOrder: 8 },
  validation: { label: "Validation", icon: "CheckCircle2", color: "text-warning", sortOrder: 9 },
  trainual: { label: "Trainual", icon: "BookOpen", color: "text-scout-purple", sortOrder: 10 },
  compliance: { label: "Compliance", icon: "Shield", color: "text-danger", sortOrder: 11 },
  objections_concerns: { label: "Objections & Concerns", icon: "AlertTriangle", color: "text-danger", sortOrder: 12 },
  behavioral_signals: { label: "Behavioral Signals", icon: "Activity", color: "text-info", sortOrder: 13 },
  engagement: { label: "Engagement", icon: "Zap", color: "text-success", sortOrder: 14 },
  external_research: { label: "External Research", icon: "Search", color: "text-muted", sortOrder: 15 },
  ai_scout: { label: "AI Scout Intelligence", icon: "Bot", color: "text-scout-purple", sortOrder: 16 },
  predictive_scores: { label: "Predictive Scores", icon: "BarChart3", color: "text-warning", sortOrder: 17 },
  metadata_audit: { label: "Metadata & Audit", icon: "Database", color: "text-muted", sortOrder: 18 },
};

export function getFieldsByCategory(category: FieldCategory): ProfileField[] {
  return PROFILE_FIELDS.filter((f) => f.category === category);
}

export function getSortedCategories(): FieldCategory[] {
  return (Object.keys(CATEGORY_META) as FieldCategory[]).sort(
    (a, b) => CATEGORY_META[a].sortOrder - CATEGORY_META[b].sortOrder
  );
}

export function getManualFields(): ProfileField[] {
  return PROFILE_FIELDS.filter((f) => f.source === "manual");
}

export function getAutoFields(): ProfileField[] {
  return PROFILE_FIELDS.filter((f) => f.source !== "manual");
}

export function getFieldByName(name: string): ProfileField | undefined {
  return PROFILE_FIELDS.find((f) => f.name === name);
}

export function isValidFieldName(name: string): boolean {
  return PROFILE_FIELDS.some((f) => f.name === name);
}
