/** Database types matching the Supabase schema in supabase/migrations/ — see docs/data-model.md */

import type {
  Workflow,
  WorkflowInsert,
  WorkflowVersion,
  WorkflowVersionInsert,
  WorkflowStep,
  WorkflowStepInsert,
  WorkflowEnrollment,
  WorkflowEnrollmentInsert,
  WorkflowStepLog,
  WorkflowStepLogInsert,
  WorkflowABTest,
  WorkflowABTestInsert,
  WorkflowApproval,
  WorkflowApprovalInsert,
} from "@/lib/workflows/types";

import type {
  CandidateIntelligence,
  CandidateIntelligenceInsert,
  CallLog,
  CallLogInsert,
  CandidateScoreHistory,
  CandidateScoreHistoryInsert,
  ObjectionRegistry,
  ObjectionRegistryInsert,
  FranchiseePerformance,
  FranchiseePerformanceInsert,
  MarketSignal,
  MarketSignalInsert,
} from "@/lib/intelligence/types";

/** User roles in the system */
export type UserRole = "rep" | "marketing" | "leadership" | "admin" | "operator" | "specialist";

/** Users table — app accounts, roles, GHL user mapping */
export interface User {
  id: string;
  email: string;
  full_name: string;
  role: UserRole;
  ghl_user_id: string | null;
  is_active: boolean;
  created_at: string;
  updated_at: string;
  last_login_at: string | null;
}

/** Categories of Scout's learned memory about a user */
export type MemoryType = "preference" | "pattern" | "context" | "note";

/** How a memory was created */
export type MemorySource = "inferred" | "explicit" | "observed";

/** User memory table — Scout's learned context per user */
export interface UserMemory {
  id: string;
  user_id: string;
  memory_type: MemoryType;
  memory_key: string;
  memory_value: string;
  confidence: number;
  source: MemorySource;
  last_accessed_at: string | null;
  created_at: string;
  updated_at: string;
}

/** Message in a conversation history */
export interface ConversationMessage {
  role: "user" | "assistant";
  content: string;
  timestamp: string;
}

/** Sessions table — conversation tracking between users and Scout */
export interface Session {
  id: string;
  user_id: string;
  conversation_history: ConversationMessage[];
  context_summary: string | null;
  ghl_contact_focus: string | null;
  is_active: boolean;
  started_at: string;
  last_activity_at: string;
  ended_at: string | null;
}

/** Types of actions Scout can draft */
export type ActionType = "message" | "task" | "stage_move" | "appointment" | "note";

/** Status of a Scout action through the Draft → Review → Confirm flow */
export type ActionStatus = "drafted" | "confirmed" | "cancelled" | "executed" | "failed";

/** Scout action logs table — immutable audit log */
export interface ScoutActionLog {
  id: string;
  user_id: string;
  session_id: string;
  action_type: ActionType;
  action_status: ActionStatus;
  ghl_contact_id: string | null;
  draft_content: Record<string, unknown>;
  final_content: Record<string, unknown> | null;
  ghl_response: Record<string, unknown> | null;
  error_message: string | null;
  created_at: string;
  confirmed_at: string | null;
  executed_at: string | null;
}

/**
 * Categories for knowledge base documents.
 * Organized around 4 growth pillars:
 *   1. More leads (marketing, lead_generation)
 *   2. Better conversion (pipeline, objections, fdd, ideal_candidate, competitors, conversion_playbook)
 *   3. Faster onboarding (training, franchisee_playbook, onboarding_ops)
 *   4. More houses (coaching, territory, industry, deal_execution)
 * Plus: cross-cutting (brand, operations, business_planning, governance, contact-notes)
 */
export type KnowledgeCategory =
  // Pillar 1: More franchise prospect leads
  | "marketing"
  | "lead_generation"
  // Pillar 2: Converting more prospects
  | "pipeline"
  | "objections"
  | "fdd"
  | "ideal_candidate"
  | "competitors"
  | "conversion_playbook"
  // Pillar 3: Getting franchisees up and running quicker
  | "training"
  | "franchisee_playbook"
  | "onboarding_ops"
  // Pillar 4: Getting franchisees to buy more houses
  | "coaching"
  | "territory"
  | "industry"
  | "deal_execution"
  // Cross-cutting
  | "brand"
  | "operations"
  | "business_planning"
  | "governance"
  | "contact-notes";

/** Knowledge documents table — franchise knowledge injected into Scout's prompt */
export interface KnowledgeDocument {
  id: string;
  title: string;
  category: KnowledgeCategory;
  content: string;
  is_active: boolean;
  priority: number;
  token_count: number | null;
  created_at: string;
  updated_at: string;
  updated_by: string | null;
}

/** App settings table — key-value configuration store */
export interface AppSetting {
  id: string;
  setting_key: string;
  setting_value: Record<string, unknown>;
  description: string | null;
  is_encrypted: boolean;
  created_at: string;
  updated_at: string;
}

/** Alert types generated by the accountability engine */
export type AlertType =
  | "speed_to_lead"
  | "stale_lead"
  | "attempt_block"
  | "connection_followup"
  | "no_show"
  | "validation_stale"
  | "fdd_window"
  | "closing_stall"
  | "nurture_archive";

/** Alert severity levels */
export type AlertSeverity = "low" | "medium" | "high" | "critical";

/** Inactivity alerts table — accountability engine alerts */
export interface InactivityAlert {
  id: string;
  alert_type: AlertType;
  severity: AlertSeverity;
  user_id: string | null;
  ghl_contact_id: string | null;
  pipeline_stage: string | null;
  message: string;
  details: Record<string, unknown> | null;
  is_resolved: boolean;
  resolved_by: string | null;
  resolved_at: string | null;
  created_at: string;
}

// ─── EOS (Entrepreneurial Operating System) Types ────────────────────────────

// ─── Territory Market Data Types ─────────────────────────────────────────────

export type MarketDataSource =
  | "census"
  | "zillow"
  | "attom"
  | "bls"
  | "manual"
  | "scout"
  | "mastersuite"
  | "calculated";

/** Territory market data — EAV row */
export interface TerritoryMarketData {
  id: string;
  TerritorySlug: string;
  field_name: string;
  field_value: string | null;
  source: MarketDataSource;
  source_date: string | null;
  updated_at: string;
  updated_by: string | null;
}

export type EosSource = "manual" | "ai";
export type EosTerritorySource = "manual" | "ai" | "carried_forward";
export type EosGoalType = "houses_purchased" | "gross_profit" | "quality_of_life";
export type EosHabitGrade = "A" | "B" | "C" | "D" | "F";
export type EosRockStatus = "not_done" | "on_track" | "off_track" | "complete";

/** Contact EOS — goals (one row per contact) */
export interface EosContactGoals {
  id: string;
  contact_id: string;
  income_goal: string | null;
  lifestyle_goal: string | null;
  qol_goal: string | null;
  source: EosSource;
  updated_at: string;
}

/** Contact EOS — issues */
export interface EosContactIssue {
  id: string;
  contact_id: string;
  Issue: string;
  is_done: boolean;
  source: EosSource;
  created_at: string;
  updated_at: string;
}

/** Contact EOS — todos */
export interface EosContactTodo {
  id: string;
  contact_id: string;
  Todo: string;
  is_done: boolean;
  owner_user_id: string | null;
  source: EosSource;
  created_at: string;
  updated_at: string;
}

/** Contact EOS — habits (recurring practices that follow the person) */
export type EosHabitCadence = "daily" | "weekly" | "biweekly" | "monthly" | "quarterly";
export interface EosContactHabit {
  id: string;
  contact_id: string;
  habit_text: string;
  cadence: EosHabitCadence;
  grade: EosHabitGrade | null;
  sort_order: number;
  source: EosSource;
  created_at: string;
  updated_at: string;
}

/** Territory EOS — goals (3 rows per territory: houses, profit, qol) */
export interface EosTerritoryGoal {
  id: string;
  TerritorySlug: string;
  goal_type: EosGoalType;
  actual: string | null;
  current_year_goal: string | null;
  year_5_goal: string | null;
  year_25_goal: string | null;
  updated_at: string;
}

/** Territory EOS — scorecard metrics */
export interface EosTerritoryScorecard {
  id: string;
  TerritorySlug: string;
  metric_key: string;
  metric_label: string;
  goal_value: string | null;
  sort_order: number;
  updated_at: string;
}

/** Territory EOS — budget line items */
export interface EosTerritoryBudget {
  id: string;
  TerritorySlug: string;
  description: string;
  amount: number;
  sort_order: number;
  updated_at: string;
}

/** Territory EOS — lead channels */
export interface EosTerritoryLeadChannel {
  id: string;
  TerritorySlug: string;
  channel_name: string;
  is_active: boolean;
  sort_order: number;
  updated_at: string;
}

/** Territory EOS — habits */
export interface EosTerritoryHabit {
  id: string;
  TerritorySlug: string;
  habit_key: string;
  habit_label: string;
  grade: EosHabitGrade | null;
  sort_order: number;
  updated_at: string;
}

/** Territory EOS — rocks (90-day priorities) */
export interface EosTerritoryRock {
  id: string;
  TerritorySlug: string;
  Rock: string;
  status: EosRockStatus;
  quarter: number | null;
  year: number | null;
  created_at: string;
  updated_at: string;
}

/** Territory EOS — issues */
export interface EosTerritoryIssue {
  id: string;
  TerritorySlug: string;
  Issue: string;
  is_done: boolean;
  source: EosTerritorySource;
  origin_contact_id: string | null;
  created_at: string;
  updated_at: string;
}

/** Territory EOS — todos */
export interface EosTerritoryTodo {
  id: string;
  TerritorySlug: string;
  Todo: string;
  is_done: boolean;
  owner_user_id: string | null;
  source: EosTerritorySource;
  origin_contact_id: string | null;
  created_at: string;
  updated_at: string;
}

/**
 * NOTE: The canonical Database type is in types/supabase.ts (auto-generated).
 * This manual version is kept only as reference — do not import it.
 * Import Database from "@/types/supabase" instead.
 */
interface _DatabaseRef {
  public: {
    Tables: {
      users: {
        Row: User;
        Insert: Omit<User, "id" | "created_at" | "updated_at" | "last_login_at"> & {
          id?: string;
          created_at?: string;
          updated_at?: string;
          last_login_at?: string | null;
        };
        Update: Partial<Omit<User, "id" | "created_at">>;
      };
      user_memory: {
        Row: UserMemory;
        Insert: Omit<UserMemory, "id" | "created_at" | "updated_at" | "last_accessed_at"> & {
          id?: string;
          created_at?: string;
          updated_at?: string;
          last_accessed_at?: string | null;
        };
        Update: Partial<Omit<UserMemory, "id" | "created_at">>;
      };
      sessions: {
        Row: Session;
        Insert: Omit<Session, "id" | "started_at" | "last_activity_at"> & {
          id?: string;
          started_at?: string;
          last_activity_at?: string;
        };
        Update: Partial<Omit<Session, "id" | "started_at">>;
      };
      scout_action_logs: {
        Row: ScoutActionLog;
        Insert: Omit<ScoutActionLog, "id" | "created_at"> & {
          id?: string;
          created_at?: string;
        };
        Update: Partial<Omit<ScoutActionLog, "id" | "created_at">>;
      };
      knowledge_documents: {
        Row: KnowledgeDocument;
        Insert: Omit<KnowledgeDocument, "id" | "created_at" | "updated_at"> & {
          id?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: Partial<Omit<KnowledgeDocument, "id" | "created_at">>;
      };
      app_settings: {
        Row: AppSetting;
        Insert: Omit<AppSetting, "id" | "created_at" | "updated_at"> & {
          id?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: Partial<Omit<AppSetting, "id" | "created_at">>;
      };
      inactivity_alerts: {
        Row: InactivityAlert;
        Insert: Omit<InactivityAlert, "id" | "created_at"> & {
          id?: string;
          created_at?: string;
        };
        Update: Partial<Omit<InactivityAlert, "id" | "created_at">>;
      };
      workflows: {
        Row: Workflow;
        Insert: WorkflowInsert;
        Update: Partial<Omit<Workflow, "id" | "created_at">>;
      };
      workflow_versions: {
        Row: WorkflowVersion;
        Insert: WorkflowVersionInsert;
        Update: Partial<Omit<WorkflowVersion, "id" | "created_at">>;
      };
      workflow_steps: {
        Row: WorkflowStep;
        Insert: WorkflowStepInsert;
        Update: Partial<Omit<WorkflowStep, "id" | "created_at">>;
      };
      workflow_enrollments: {
        Row: WorkflowEnrollment;
        Insert: WorkflowEnrollmentInsert;
        Update: Partial<Omit<WorkflowEnrollment, "id" | "enrolled_at">>;
      };
      workflow_step_logs: {
        Row: WorkflowStepLog;
        Insert: WorkflowStepLogInsert;
        Update: Partial<Omit<WorkflowStepLog, "id" | "created_at">>;
      };
      workflow_ab_tests: {
        Row: WorkflowABTest;
        Insert: WorkflowABTestInsert;
        Update: Partial<Omit<WorkflowABTest, "id" | "created_at">>;
      };
      workflow_approvals: {
        Row: WorkflowApproval;
        Insert: WorkflowApprovalInsert;
        Update: Partial<Omit<WorkflowApproval, "id" | "submitted_at">>;
      };
      candidate_intelligence: {
        Row: CandidateIntelligence;
        Insert: CandidateIntelligenceInsert;
        Update: Partial<Omit<CandidateIntelligence, "id" | "created_at">>;
      };
      call_logs: {
        Row: CallLog;
        Insert: CallLogInsert;
        Update: Partial<Omit<CallLog, "id" | "created_at">>;
      };
      candidate_score_history: {
        Row: CandidateScoreHistory;
        Insert: CandidateScoreHistoryInsert;
        Update: Partial<Omit<CandidateScoreHistory, "id" | "created_at">>;
      };
      objection_registry: {
        Row: ObjectionRegistry;
        Insert: ObjectionRegistryInsert;
        Update: Partial<Omit<ObjectionRegistry, "id" | "created_at">>;
      };
      franchisee_performance: {
        Row: FranchiseePerformance;
        Insert: FranchiseePerformanceInsert;
        Update: Partial<Omit<FranchiseePerformance, "id" | "created_at">>;
      };
      market_signals: {
        Row: MarketSignal;
        Insert: MarketSignalInsert;
        Update: Partial<Omit<MarketSignal, "id" | "observed_at">>;
      };
    };
  };
}
