/** Database types matching the Supabase schema defined in architecture.md */

/** User roles in the system */
export type UserRole = "rep" | "marketing" | "leadership";

/** Users table — app accounts, roles, GHL user mapping */
export interface User {
  id: string;
  email: string;
  full_name: string;
  role: UserRole;
  ghl_user_id: string | null;
  is_active: boolean;
  created_at: string;
  updated_at: string;
  last_login_at: string | null;
}

/** Categories of Scout's learned memory about a user */
export type MemoryType = "preference" | "pattern" | "context" | "note";

/** How a memory was created */
export type MemorySource = "inferred" | "explicit" | "observed";

/** User memory table — Scout's learned context per user */
export interface UserMemory {
  id: string;
  user_id: string;
  memory_type: MemoryType;
  memory_key: string;
  memory_value: string;
  confidence: number;
  source: MemorySource;
  last_accessed_at: string | null;
  created_at: string;
  updated_at: string;
}

/** Message in a conversation history */
export interface ConversationMessage {
  role: "user" | "assistant";
  content: string;
  timestamp: string;
}

/** Sessions table — conversation tracking between users and Scout */
export interface Session {
  id: string;
  user_id: string;
  conversation_history: ConversationMessage[];
  context_summary: string | null;
  ghl_contact_focus: string | null;
  is_active: boolean;
  started_at: string;
  last_activity_at: string;
  ended_at: string | null;
}

/** Types of actions Scout can draft */
export type ActionType = "message" | "task" | "stage_move" | "appointment" | "note";

/** Status of a Scout action through the Draft → Review → Confirm flow */
export type ActionStatus = "drafted" | "confirmed" | "cancelled" | "executed" | "failed";

/** Scout action logs table — immutable audit log */
export interface ScoutActionLog {
  id: string;
  user_id: string;
  session_id: string;
  action_type: ActionType;
  action_status: ActionStatus;
  ghl_contact_id: string | null;
  draft_content: Record<string, unknown>;
  final_content: Record<string, unknown> | null;
  ghl_response: Record<string, unknown> | null;
  error_message: string | null;
  created_at: string;
  confirmed_at: string | null;
  executed_at: string | null;
}

/** Categories for knowledge base documents */
export type KnowledgeCategory =
  | "brand"
  | "pipeline"
  | "objections"
  | "competitors"
  | "industry"
  | "fdd"
  | "contact-notes";

/** Knowledge documents table — franchise knowledge injected into Scout's prompt */
export interface KnowledgeDocument {
  id: string;
  title: string;
  category: KnowledgeCategory;
  content: string;
  is_active: boolean;
  priority: number;
  token_count: number | null;
  created_at: string;
  updated_at: string;
  updated_by: string | null;
}

/** App settings table — key-value configuration store */
export interface AppSetting {
  id: string;
  setting_key: string;
  setting_value: Record<string, unknown>;
  description: string | null;
  is_encrypted: boolean;
  created_at: string;
  updated_at: string;
}

/** Alert types generated by the accountability engine */
export type AlertType =
  | "speed_to_lead"
  | "stale_lead"
  | "attempt_block"
  | "connection_followup"
  | "no_show"
  | "validation_stale"
  | "fdd_window"
  | "closing_stall"
  | "nurture_archive";

/** Alert severity levels */
export type AlertSeverity = "low" | "medium" | "high" | "critical";

/** Inactivity alerts table — accountability engine alerts */
export interface InactivityAlert {
  id: string;
  alert_type: AlertType;
  severity: AlertSeverity;
  user_id: string | null;
  ghl_contact_id: string | null;
  pipeline_stage: string | null;
  message: string;
  details: Record<string, unknown> | null;
  is_resolved: boolean;
  resolved_by: string | null;
  resolved_at: string | null;
  created_at: string;
}

/** Supabase Database type for typed client access */
export interface Database {
  public: {
    Tables: {
      users: {
        Row: User;
        Insert: Omit<User, "id" | "created_at" | "updated_at" | "last_login_at"> & {
          id?: string;
          created_at?: string;
          updated_at?: string;
          last_login_at?: string | null;
        };
        Update: Partial<Omit<User, "id" | "created_at">>;
      };
      user_memory: {
        Row: UserMemory;
        Insert: Omit<UserMemory, "id" | "created_at" | "updated_at" | "last_accessed_at"> & {
          id?: string;
          created_at?: string;
          updated_at?: string;
          last_accessed_at?: string | null;
        };
        Update: Partial<Omit<UserMemory, "id" | "created_at">>;
      };
      sessions: {
        Row: Session;
        Insert: Omit<Session, "id" | "started_at" | "last_activity_at"> & {
          id?: string;
          started_at?: string;
          last_activity_at?: string;
        };
        Update: Partial<Omit<Session, "id" | "started_at">>;
      };
      scout_action_logs: {
        Row: ScoutActionLog;
        Insert: Omit<ScoutActionLog, "id" | "created_at"> & {
          id?: string;
          created_at?: string;
        };
        Update: Partial<Omit<ScoutActionLog, "id" | "created_at">>;
      };
      knowledge_documents: {
        Row: KnowledgeDocument;
        Insert: Omit<KnowledgeDocument, "id" | "created_at" | "updated_at"> & {
          id?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: Partial<Omit<KnowledgeDocument, "id" | "created_at">>;
      };
      app_settings: {
        Row: AppSetting;
        Insert: Omit<AppSetting, "id" | "created_at" | "updated_at"> & {
          id?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: Partial<Omit<AppSetting, "id" | "created_at">>;
      };
      inactivity_alerts: {
        Row: InactivityAlert;
        Insert: Omit<InactivityAlert, "id" | "created_at"> & {
          id?: string;
          created_at?: string;
        };
        Update: Partial<Omit<InactivityAlert, "id" | "created_at">>;
      };
    };
  };
}
