/** Central type exports for the NAH Franchise OS */

export type {
  UserRole,
  User,
  MemoryType,
  MemorySource,
  UserMemory,
  ConversationMessage,
  Session,
  ActionType,
  ActionStatus,
  ScoutActionLog,
  KnowledgeCategory,
  KnowledgeDocument,
  AppSetting,
  AlertType,
  AlertSeverity,
  InactivityAlert,
  Database,
} from "./database";

export type {
  GHLContact,
  GHLCustomField,
  GHLContactSearchParams,
  GHLContactUpdatePayload,
  GHLPipeline,
  GHLPipelineStage,
  GHLOpportunity,
  GHLOpportunitySearchParams,
  GHLOpportunityUpdatePayload,
  GHLTask,
  GHLTaskCreatePayload,
  GHLTaskUpdatePayload,
  GHLAppointment,
  GHLAppointmentCreatePayload,
  GHLFreeSlot,
  GHLConversation,
  GHLMessage,
  GHLSendMessagePayload,
  GHLSendSMSPayload,
  GHLSendEmailPayload,
  GHLWorkflow,
  GHLNote,
  GHLApiResponse,
  GHLApiError,
} from "./ghl";

export type {
  ScoutToolName,
  ChatRole,
  ChatMessage,
  DraftedActionType,
  DraftedActionStatus,
  DraftedAction,
  DraftedMessagePayload,
  DraftedTaskPayload,
  DraftedStageMovePayload,
  DraftedAppointmentPayload,
  ScoutChatRequest,
  ScoutChatResponse,
  ScoutToolDefinition,
} from "./scout";
