/** GHL module — re-exports all GHL client functions + custom field resolver */

export {
  resolveFieldId,
  resolveCustomFields,
  refreshFieldCache,
  ensureCustomField,
} from "./custom-fields";

export {
  getContact,
  updateContact,
  upsertContact,
  searchContacts,
  getContactHistory,
  getPipelines,
  searchOpportunities,
  searchOpportunitiesPaginated,
  countContactsByFilter,
  countOpportunitiesByStatus,
  getStageIdByName,
  movePipelineStage,
  createOpportunity,
  getTasks,
  createTask,
  updateTask,
  getCalendarFreeSlots,
  createAppointment,
  getAppointments,
  getConversations,
  getConversationMessages,
  markConversationRead,
  getCallRecording,
  getCallTranscription,
  sendMessage,
  getWorkflows,
  triggerWorkflow,
  getNotes,
  addNote,
  GHLError,
} from "./client";
