export type AgentCategoryKey =
  | "marketing"
  | "lead-management"
  | "franchisee-management"
  | "site-development"
  | "operations"
  | "planned";

export type AgentStatus = "active" | "paused" | "planned" | "needs-review";
export type AgentTrustLevel = "read-only" | "drafts-only" | "approval-required" | "manual-only";

export interface AgentCategory {
  key: AgentCategoryKey;
  label: string;
  summary: string;
}

export interface AgentManualRunEndpoint {
  url: string;
  method: "GET" | "POST";
  body?: Record<string, unknown>;
}

export interface AgentPortrait {
  initials: string;
  accent: string;
  background: string;
  jacket: string;
  expression: string;
}

export interface AgentRegistryEntry {
  name: string;
  label: string;
  roleTitle: string;
  category: AgentCategoryKey;
  status: AgentStatus;
  trigger: string;
  description: string;
  mission: string;
  uses: string[];
  howItWorks: string[];
  dataSources: string[];
  guardrails: string[];
  canDo: string[];
  cannotDo: string[];
  costPerRunEstimate: string;
  trustLevel: AgentTrustLevel;
  supportsManualRun: boolean;
  supportsConversation: boolean;
  portrait: AgentPortrait;
  manualRun?: AgentManualRunEndpoint;
}

export interface AgentRuntimeStats {
  enabled: boolean;
  runsMTD: number;
  suggestionsMTD: number;
  costEstMTD: string;
  lastRunAt: string | null;
  lastStatus: string | null;
  lastError: string | null;
  trainingNotes: string;
  trainingUpdatedAt: string | null;
  trainingUpdatedBy: string | null;
}

export type AgentTeamCard = AgentRegistryEntry & AgentRuntimeStats;

export const AGENT_CATEGORIES: AgentCategory[] = [
  {
    key: "marketing",
    label: "Marketing",
    summary: "Find demand, spot channel gaps, and make lead generation visible.",
  },
  {
    key: "lead-management",
    label: "Lead Management",
    summary: "Help reps understand prospects, prep calls, and keep follow-up moving.",
  },
  {
    key: "franchisee-management",
    label: "Franchisee Management",
    summary: "Protect onboarding, runway, coaching, and performance habits after award.",
  },
  {
    key: "site-development",
    label: "Site Development",
    summary: "Support territory, market, property, and local execution intelligence.",
  },
  {
    key: "operations",
    label: "Operations",
    summary: "Watch data quality, workflows, automations, and system reliability.",
  },
  {
    key: "planned",
    label: "Planned",
    summary: "Future teammates we want to add when the operating model is ready.",
  },
];

export const AGENT_REGISTRY: AgentRegistryEntry[] = [
  {
    name: "post-call",
    label: "Call Captain",
    roleTitle: "Post-Call Intelligence Agent",
    category: "lead-management",
    status: "active",
    trigger: "Read.ai webhook after calls, plus manual Generate button",
    description: "Turns call recordings into structured takeaways, profile data, next steps, and coaching signals.",
    mission: "Make every call compound into better follow-up, better profiles, and better franchise decisions.",
    uses: ["Extracts prospect facts from calls", "Creates next-step suggestions", "Improves profile completeness"],
    howItWorks: [
      "Receives or processes the call transcript.",
      "Extracts key facts, objections, commitments, and next actions.",
      "Auto-saves high-confidence facts and queues lower-confidence items for review.",
      "Logs what it found so the team can inspect and improve it.",
    ],
    dataSources: ["Read.ai transcripts", "Calls", "Contacts", "Journeys", "Call data extractions"],
    guardrails: ["Does not send messages", "Lower-confidence findings go to review", "Human can override call data"],
    canDo: ["Summarize calls", "Find missing follow-up", "Improve contact profiles"],
    cannotDo: ["Close a candidate", "Send customer messages", "Override human judgment"],
    costPerRunEstimate: "$0.002/run est.",
    trustLevel: "drafts-only",
    supportsManualRun: false,
    supportsConversation: true,
    portrait: {
      initials: "CC",
      accent: "from-sky-500 to-cyan-400",
      background: "from-sky-50 via-white to-cyan-50",
      jacket: "bg-sky-700",
      expression: "Focused",
    },
  },
  {
    name: "contact-research",
    label: "Prospect Profiler",
    roleTitle: "Contact Research Agent",
    category: "lead-management",
    status: "active",
    trigger: "New contact, Research button, and weekly research cron",
    description: "Builds richer prospect context so reps understand the person behind the lead.",
    mission: "Help the team know who they are talking to before the first serious conversation.",
    uses: ["Researches candidate background", "Suggests profile enrichment", "Flags likely strengths and gaps"],
    howItWorks: [
      "Reads the contact record and available context.",
      "Researches or infers useful profile fields.",
      "Auto-writes high-confidence basics when allowed.",
      "Queues uncertain findings as suggestions for a human to approve.",
    ],
    dataSources: ["Contacts", "Contact profile data", "Suggestion queue", "Public/contextual research"],
    guardrails: ["Does not invent facts", "Medium/low confidence goes to review", "Writes only allowed high-confidence fields"],
    canDo: ["Enrich prospect context", "Create reviewable suggestions", "Improve lead scoring inputs"],
    cannotDo: ["Guarantee personal facts", "Make qualification decisions alone", "Message prospects"],
    costPerRunEstimate: "$0.002/run est.",
    trustLevel: "drafts-only",
    supportsManualRun: false,
    supportsConversation: true,
    portrait: {
      initials: "PP",
      accent: "from-indigo-500 to-violet-400",
      background: "from-indigo-50 via-white to-violet-50",
      jacket: "bg-indigo-700",
      expression: "Curious",
    },
  },
  {
    name: "pre-call-brief",
    label: "Brief Builder",
    roleTitle: "Pre-Call Brief Agent",
    category: "lead-management",
    status: "active",
    trigger: "Daily 7am cron for scheduled calls",
    description: "Prepares reps before calls with context, likely objections, and recommended angles.",
    mission: "Make every rep walk into the next call prepared instead of cold.",
    uses: ["Builds call prep briefs", "Surfaces recent activity", "Frames questions and risks"],
    howItWorks: [
      "Looks at scheduled calls for the day.",
      "Pulls contact, journey, call, and profile context.",
      "Generates a concise briefing for the rep.",
      "Stores the brief for review before the call.",
    ],
    dataSources: ["Calendar calls", "Contacts", "Journeys", "Profiles", "Prior calls"],
    guardrails: ["Advisory only", "Does not contact prospects", "Uses known app data"],
    canDo: ["Prepare a rep", "Explain what matters", "Highlight missing context"],
    cannotDo: ["Run the call", "Promise accuracy if source data is stale", "Send outreach"],
    costPerRunEstimate: "$0.002/run est.",
    trustLevel: "read-only",
    supportsManualRun: false,
    supportsConversation: true,
    portrait: {
      initials: "BB",
      accent: "from-amber-500 to-orange-400",
      background: "from-amber-50 via-white to-orange-50",
      jacket: "bg-amber-700",
      expression: "Ready",
    },
  },
  {
    name: "reengagement-signal",
    label: "Revival Scout",
    roleTitle: "Re-Engagement Signal Agent",
    category: "marketing",
    status: "active",
    trigger: "Monthly scan on the 1st of each month",
    description: "Finds older contacts who may be worth waking back up with the right message.",
    mission: "Turn dormant lead lists into timely second chances without spamming everyone.",
    uses: ["Scans stale leads", "Identifies reactivation opportunities", "Suggests next campaigns"],
    howItWorks: [
      "Looks for contacts that have gone quiet.",
      "Checks context, fit, and recent signals.",
      "Creates a re-engagement recommendation.",
      "Leaves outreach to approved workflow/message paths.",
    ],
    dataSources: ["Contacts", "Journeys", "Activity history", "Pipeline state"],
    guardrails: ["No auto-sending", "Human approval required for outreach", "Prioritizes fit and timing"],
    canDo: ["Find old opportunities", "Recommend campaign angles", "Explain why a lead is worth revisiting"],
    cannotDo: ["Send campaigns by itself", "Override opt-out/suppression rules", "Guarantee intent"],
    costPerRunEstimate: "$0.002/run est.",
    trustLevel: "approval-required",
    supportsManualRun: false,
    supportsConversation: true,
    portrait: {
      initials: "RS",
      accent: "from-emerald-500 to-teal-400",
      background: "from-emerald-50 via-white to-teal-50",
      jacket: "bg-emerald-700",
      expression: "Alert",
    },
  },
  {
    name: "journey-brief",
    label: "Journey Coach",
    roleTitle: "Journey Brief Agent",
    category: "franchisee-management",
    status: "active",
    trigger: "Stage change, call graded, property sync, and nightly cron",
    description: "Creates an operating brief around where a candidate or franchisee is in the journey.",
    mission: "Keep the team aligned on what each journey needs next.",
    uses: ["Summarizes journey state", "Highlights risks and next actions", "Connects sales, onboarding, and runway context"],
    howItWorks: [
      "Reads the active journey and pipeline state.",
      "Pulls recent calls, notes, and performance signals.",
      "Summarizes where the journey stands.",
      "Flags what should happen next.",
    ],
    dataSources: ["Journeys", "Pipeline state", "Calls", "Contacts", "Territories"],
    guardrails: ["Advisory only", "Does not move stages by itself", "Uses app data as source of truth"],
    canDo: ["Create journey summaries", "Explain current risk", "Suggest next operating moves"],
    cannotDo: ["Award a territory", "Move stages without approval", "Replace rep judgment"],
    costPerRunEstimate: "$0.002/run est.",
    trustLevel: "read-only",
    supportsManualRun: false,
    supportsConversation: true,
    portrait: {
      initials: "JC",
      accent: "from-blue-600 to-indigo-400",
      background: "from-blue-50 via-white to-indigo-50",
      jacket: "bg-blue-800",
      expression: "Steady",
    },
  },
  {
    name: "territory-market",
    label: "Market Mapper",
    roleTitle: "Territory Market Research Agent",
    category: "site-development",
    status: "active",
    trigger: "Territory presented, Research button, and 30-day cron",
    description: "Researches territories and market conditions so site decisions have context.",
    mission: "Help franchisees and leadership understand the local market before decisions get expensive.",
    uses: ["Researches territory conditions", "Creates market-data suggestions", "Supports site and territory planning"],
    howItWorks: [
      "Reads the territory and owner context.",
      "Researches market signals and competitive context.",
      "Creates suggested market data updates.",
      "Routes findings into reviewable records.",
    ],
    dataSources: ["Territories", "Market data", "MasterSuite mirrors", "Suggestion queue"],
    guardrails: ["Research is reviewed", "Does not change territory ownership", "Does not make investment decisions"],
    canDo: ["Map market signals", "Find missing territory context", "Support planning conversations"],
    cannotDo: ["Approve a site", "Guarantee market outcomes", "Replace field validation"],
    costPerRunEstimate: "$0.002/run est.",
    trustLevel: "drafts-only",
    supportsManualRun: false,
    supportsConversation: true,
    portrait: {
      initials: "MM",
      accent: "from-lime-500 to-green-400",
      background: "from-lime-50 via-white to-green-50",
      jacket: "bg-lime-700",
      expression: "Searching",
    },
  },
  {
    name: "data-intelligence",
    label: "Data Steward",
    roleTitle: "Data Intelligence Agent",
    category: "operations",
    status: "active",
    trigger: "Manual data coverage audit, future weekly cron",
    description: "Maps what data exists, where it lives, and what Scout can safely retrieve.",
    mission: "Make the system trustworthy by keeping source-of-truth and retrieval gaps visible.",
    uses: ["Audits data coverage", "Explains source-of-truth issues", "Finds retrieval gaps"],
    howItWorks: [
      "Inspects app data coverage and known sources.",
      "Compares what exists against what operators expect.",
      "Reports gaps, stale sources, and missing routes.",
      "Helps prioritize data cleanup work.",
    ],
    dataSources: ["Supabase", "MasterSuite mirrors", "Integration logs", "Scout tool definitions"],
    guardrails: ["Read/audit focused", "Does not rewrite business data", "Escalates uncertain gaps"],
    canDo: ["Audit data trust", "Explain where fields come from", "Recommend cleanup priorities"],
    cannotDo: ["Fix every source automatically", "Bypass source-of-truth rules", "Use GHL as reporting truth"],
    costPerRunEstimate: "$0.002/run est.",
    trustLevel: "read-only",
    supportsManualRun: true,
    supportsConversation: true,
    manualRun: { url: "/api/agents/data-intelligence/run", method: "POST" },
    portrait: {
      initials: "DS",
      accent: "from-slate-600 to-cyan-500",
      background: "from-slate-50 via-white to-cyan-50",
      jacket: "bg-slate-800",
      expression: "Precise",
    },
  },
  {
    name: "runway-pipeline-guardian",
    label: "Runway Guardian",
    roleTitle: "Runway Pipeline Guardian",
    category: "franchisee-management",
    status: "active",
    trigger: "After MasterSuite territory sync, every 30-minute cron, and Run button",
    description: "Audits runway eligibility and stage placement against MasterSuite property evidence.",
    mission: "Keep franchisees in the right runway stage so coaching attention goes where it belongs.",
    uses: ["Checks runway eligibility", "Finds stage placement mistakes", "Protects coaching visibility"],
    howItWorks: [
      "Reads active territories and current runway rows.",
      "Compares them to purchase, completion, offer, and running evidence.",
      "Flags missing, unexpected, duplicate, or mismatched rows.",
      "Can repair only through explicit guarded paths.",
    ],
    dataSources: ["Territories", "Journey pipeline state", "MasterSuite properties", "Runway stages"],
    guardrails: ["Audit first", "Repair is explicit", "Logs every guardian run"],
    canDo: ["Detect runway drift", "Explain stage mismatches", "Support reliable coaching boards"],
    cannotDo: ["Change property facts", "Invent runway evidence", "Hide critical issues"],
    costPerRunEstimate: "$0.002/run est.",
    trustLevel: "manual-only",
    supportsManualRun: true,
    supportsConversation: true,
    manualRun: { url: "/api/agents/runway-pipeline-guardian/run", method: "POST", body: { repair: false } },
    portrait: {
      initials: "RG",
      accent: "from-rose-500 to-red-400",
      background: "from-rose-50 via-white to-red-50",
      jacket: "bg-rose-800",
      expression: "Guarding",
    },
  },
  {
    name: "marketing-intelligence",
    label: "Demand Builder",
    roleTitle: "Marketing Intelligence Agent",
    category: "marketing",
    status: "active",
    trigger: "Manual channel audit now, future ad-platform sync and weekly growth review",
    description: "Summarizes lead-source coverage, EOS channel gaps, source quality, and missed channel opportunities.",
    mission: "Show what is producing leads, what is missing, and where to push next.",
    uses: ["Explain channel performance", "Find lead-gen gaps", "Recommend next tests"],
    howItWorks: [
      "Reads source performance and EOS channel coverage.",
      "Compares lead quality across channels.",
      "Finds territories or channels missing activity.",
      "Recommends next marketing tests.",
    ],
    dataSources: ["Marketing V1", "Contacts attribution", "EOS lead channels", "Scout scores"],
    guardrails: ["No fake spend data", "Google/Facebook access required", "Recommendations need human approval"],
    canDo: ["Explain marketing performance", "Find opportunity gaps", "Help plan tests"],
    cannotDo: ["Use unavailable ad data", "Spend money automatically", "Launch campaigns without approval"],
    costPerRunEstimate: "$0.002/run est.",
    trustLevel: "read-only",
    supportsManualRun: true,
    supportsConversation: true,
    manualRun: { url: "/api/agents/marketing-intelligence/run", method: "POST" },
    portrait: {
      initials: "DB",
      accent: "from-fuchsia-500 to-pink-400",
      background: "from-fuchsia-50 via-white to-pink-50",
      jacket: "bg-fuchsia-800",
      expression: "Creative",
    },
  },
  {
    name: "workflow-qa",
    label: "Automation Watch",
    roleTitle: "Workflow QA Agent",
    category: "operations",
    status: "active",
    trigger: "Manual workflow QA audit now, future scheduler/approval/delivery-sync checks",
    description: "Watches workflow health, approvals, delivery errors, and queued steps so automations stay trustworthy.",
    mission: "Make workflow automation safe enough that the team actually trusts it.",
    uses: ["Find stuck workflow steps", "Watch approval queues", "Surface delivery problems"],
    howItWorks: [
      "Reads workflow logs and enrollment state.",
      "Detects stuck, stale, or risky automation behavior.",
      "Explains what is blocked and why.",
      "Routes fixes through human approval.",
    ],
    dataSources: ["Workflow enrollments", "Step logs", "Approval queues", "Delivery sync"],
    guardrails: ["No auto-sending", "Human approval required", "SMS approval dependency respected"],
    canDo: ["Find automation risk", "Explain stuck steps", "Protect workflow trust"],
    cannotDo: ["Send customer SMS while blocked", "Bypass carrier approval", "Force live delivery proof"],
    costPerRunEstimate: "$0.002/run est.",
    trustLevel: "approval-required",
    supportsManualRun: true,
    supportsConversation: true,
    manualRun: { url: "/api/agents/workflow-qa/run", method: "POST" },
    portrait: {
      initials: "AW",
      accent: "from-cyan-500 to-blue-400",
      background: "from-cyan-50 via-white to-blue-50",
      jacket: "bg-cyan-800",
      expression: "Watching",
    },
  },
  {
    name: "eos-sync",
    label: "EOS Operator",
    roleTitle: "EOS Sync Agent",
    category: "franchisee-management",
    status: "active",
    trigger: "Manual EOS coverage audit now, future after EOS sync and before L10 review",
    description: "Audits rocks, scorecards, todos, issues, habits, lead channels, and L10-facing EOS coverage.",
    mission: "Help operating meetings reflect the real business instead of stale records.",
    uses: ["Find missing EOS data", "Explain L10 mismatches", "Surface accountability gaps"],
    howItWorks: [
      "Reads EOS mirrors and L10-facing views.",
      "Compares expected records against current records.",
      "Flags missing or stale items.",
      "Summarizes what needs cleanup before meetings.",
    ],
    dataSources: ["MasterSuite EOS", "Supabase EOS mirrors", "L10 views"],
    guardrails: ["Audits first", "Does not rewrite meeting records automatically", "Keeps source-of-truth visible"],
    canDo: ["Find EOS gaps", "Prepare L10 cleanup", "Explain missing records"],
    cannotDo: ["Run the meeting", "Assign accountability without approval", "Patch source systems blindly"],
    costPerRunEstimate: "$0.002/run est.",
    trustLevel: "read-only",
    supportsManualRun: true,
    supportsConversation: true,
    manualRun: { url: "/api/agents/eos-sync/run", method: "POST" },
    portrait: {
      initials: "EO",
      accent: "from-yellow-500 to-amber-400",
      background: "from-yellow-50 via-white to-amber-50",
      jacket: "bg-yellow-700",
      expression: "Organized",
    },
  },
  {
    name: "campaign-composer",
    label: "Campaign Composer",
    roleTitle: "Marketing Campaign Agent",
    category: "marketing",
    status: "planned",
    trigger: "Future campaign planning workspace and approved launch checklist",
    description: "Turns campaign ideas into channel plans, audiences, drafts, and review-ready launch packages.",
    mission: "Help the team move from loose marketing ideas to testable campaigns with clear ownership.",
    uses: ["Drafts campaign briefs", "Maps audiences and channels", "Creates review-ready messaging angles"],
    howItWorks: [
      "Reads lead-source performance and growth priorities.",
      "Suggests campaign themes, audience segments, and channel mix.",
      "Drafts copy and assets for review.",
      "Routes launch steps through approval before anything goes live.",
    ],
    dataSources: ["Marketing V1", "Lead sources", "Campaign history", "Brand messaging"],
    guardrails: ["No auto-launching", "Spend and sends require approval", "Uses approved brand language"],
    canDo: ["Package campaign ideas", "Draft messaging", "Recommend tests"],
    cannotDo: ["Spend ad budget", "Launch campaigns alone", "Bypass brand review"],
    costPerRunEstimate: "$0.002/run est.",
    trustLevel: "approval-required",
    supportsManualRun: false,
    supportsConversation: true,
    portrait: {
      initials: "CC",
      accent: "from-pink-500 to-rose-400",
      background: "from-pink-50 via-white to-rose-50",
      jacket: "bg-pink-800",
      expression: "Inventive",
    },
  },
  {
    name: "brand-listener",
    label: "Brand Listener",
    roleTitle: "Market Signal Agent",
    category: "marketing",
    status: "planned",
    trigger: "Future review, social, competitor, and market-signal scans",
    description: "Monitors external signals that may affect franchise demand and brand perception.",
    mission: "Give leadership an early read on what the market is saying before it shows up in the pipeline.",
    uses: ["Tracks brand signals", "Summarizes competitor movement", "Flags reputation or demand shifts"],
    howItWorks: [
      "Scans approved public sources and internal notes.",
      "Groups signals by market, channel, and urgency.",
      "Summarizes what changed and why it matters.",
      "Suggests whether marketing, sales, or leadership should respond.",
    ],
    dataSources: ["Public reviews", "Competitor pages", "Social mentions", "Internal market notes"],
    guardrails: ["Public/contextual research only", "No public posting", "Escalates sensitive signals"],
    canDo: ["Summarize market chatter", "Flag brand risks", "Spot competitor changes"],
    cannotDo: ["Reply publicly", "Represent the company", "Treat weak signals as facts"],
    costPerRunEstimate: "$0.002/run est.",
    trustLevel: "read-only",
    supportsManualRun: false,
    supportsConversation: true,
    portrait: {
      initials: "BL",
      accent: "from-purple-500 to-fuchsia-400",
      background: "from-purple-50 via-white to-fuchsia-50",
      jacket: "bg-purple-800",
      expression: "Listening",
    },
  },
  {
    name: "follow-up-concierge",
    label: "Follow-Up Concierge",
    roleTitle: "Prospect Follow-Up Agent",
    category: "lead-management",
    status: "planned",
    trigger: "Future stale-stage, missed-task, and post-call follow-up checks",
    description: "Keeps prospects from going cold by drafting next touches and surfacing overdue follow-up.",
    mission: "Make sure every qualified prospect gets the right next touch at the right time.",
    uses: ["Flags stale prospects", "Drafts follow-up messages", "Suggests next best action"],
    howItWorks: [
      "Reads pipeline stage, recent activity, and commitments.",
      "Identifies candidates who need follow-up.",
      "Drafts a recommended touch with context.",
      "Queues outreach for human approval.",
    ],
    dataSources: ["Contacts", "Journeys", "Tasks", "Calls", "Messages"],
    guardrails: ["No auto-sending", "Respects opt-outs", "Human approval required for outreach"],
    canDo: ["Find missed follow-up", "Draft outreach", "Prioritize next touches"],
    cannotDo: ["Send messages alone", "Ignore opt-out status", "Pressure prospects without review"],
    costPerRunEstimate: "$0.002/run est.",
    trustLevel: "approval-required",
    supportsManualRun: false,
    supportsConversation: true,
    portrait: {
      initials: "FC",
      accent: "from-teal-500 to-cyan-400",
      background: "from-teal-50 via-white to-cyan-50",
      jacket: "bg-teal-800",
      expression: "Helpful",
    },
  },
  {
    name: "franchisee-support",
    label: "Support Desk",
    roleTitle: "Franchisee Support Agent",
    category: "franchisee-management",
    status: "planned",
    trigger: "Future franchisee questions, SOP lookup, and support intake",
    description: "Answers franchisee/operator questions from approved company knowledge and routes gaps to the team.",
    mission: "Give franchisees faster help while turning repeated questions into better operating knowledge.",
    uses: ["Answers SOP questions", "Routes support gaps", "Summarizes recurring issues"],
    howItWorks: [
      "Reads the question and approved knowledge sources.",
      "Answers with citations or says what is missing.",
      "Creates a support note when the answer needs human follow-up.",
      "Surfaces repeated questions for SOP improvement.",
    ],
    dataSources: ["Knowledge base", "SOPs", "Training docs", "Support notes"],
    guardrails: ["Approved knowledge only", "Escalates uncertain answers", "Does not change policy"],
    canDo: ["Answer common questions", "Find relevant SOPs", "Identify knowledge gaps"],
    cannotDo: ["Create policy", "Give legal advice", "Promise operational exceptions"],
    costPerRunEstimate: "$0.002/run est.",
    trustLevel: "read-only",
    supportsManualRun: false,
    supportsConversation: true,
    portrait: {
      initials: "SD",
      accent: "from-green-500 to-emerald-400",
      background: "from-green-50 via-white to-emerald-50",
      jacket: "bg-green-800",
      expression: "Supportive",
    },
  },
  {
    name: "property-scout",
    label: "Property Scout",
    roleTitle: "Property Opportunity Agent",
    category: "site-development",
    status: "planned",
    trigger: "Future property feed, franchisee request, and local opportunity scans",
    description: "Surfaces property opportunities and local operating signals for active territories.",
    mission: "Help franchisees see promising property movement without manually checking every source.",
    uses: ["Finds property leads", "Summarizes local opportunity", "Connects property signals to territory goals"],
    howItWorks: [
      "Reads territory profile and active operating goals.",
      "Checks approved property and market feeds.",
      "Ranks opportunities by fit and confidence.",
      "Routes findings to review before action.",
    ],
    dataSources: ["Territories", "MasterSuite properties", "Property feeds", "Market data"],
    guardrails: ["Review required", "No investment decisions", "Source confidence shown"],
    canDo: ["Find property signals", "Rank opportunities", "Explain fit"],
    cannotDo: ["Approve purchases", "Guarantee deal quality", "Replace local validation"],
    costPerRunEstimate: "$0.002/run est.",
    trustLevel: "drafts-only",
    supportsManualRun: false,
    supportsConversation: true,
    portrait: {
      initials: "PS",
      accent: "from-lime-600 to-emerald-400",
      background: "from-lime-50 via-white to-emerald-50",
      jacket: "bg-lime-800",
      expression: "Scanning",
    },
  },
  {
    name: "territory-expansion",
    label: "Expansion Planner",
    roleTitle: "Territory Expansion Agent",
    category: "site-development",
    status: "planned",
    trigger: "Future expansion review, whitespace analysis, and leadership planning",
    description: "Identifies promising expansion markets, whitespace, and territory-growth paths.",
    mission: "Turn expansion planning into a repeatable, data-backed process.",
    uses: ["Maps whitespace", "Compares markets", "Recommends expansion priorities"],
    howItWorks: [
      "Reads current territory footprint and growth goals.",
      "Compares demographic, competition, and performance signals.",
      "Highlights candidate markets and risks.",
      "Prepares a leadership review summary.",
    ],
    dataSources: ["Territories", "Market data", "Demographics", "Competitor research"],
    guardrails: ["Advisory only", "Human approval required", "Flags data confidence"],
    canDo: ["Compare markets", "Find expansion gaps", "Create planning summaries"],
    cannotDo: ["Award territory rights", "Commit capital", "Promise market success"],
    costPerRunEstimate: "$0.002/run est.",
    trustLevel: "read-only",
    supportsManualRun: false,
    supportsConversation: true,
    portrait: {
      initials: "EP",
      accent: "from-blue-500 to-lime-400",
      background: "from-blue-50 via-white to-lime-50",
      jacket: "bg-blue-800",
      expression: "Strategic",
    },
  },
  {
    name: "site-readiness",
    label: "Site Readiness",
    roleTitle: "Site Readiness Agent",
    category: "site-development",
    status: "planned",
    trigger: "Future territory launch, checklist review, and readiness milestones",
    description: "Tracks whether a territory or operating location is ready for launch and ongoing execution.",
    mission: "Make site and territory readiness visible before problems become field issues.",
    uses: ["Checks readiness milestones", "Flags launch blockers", "Summarizes territory setup gaps"],
    howItWorks: [
      "Reads territory status, onboarding tasks, and launch checklist items.",
      "Compares current progress against expected readiness.",
      "Highlights blockers and missing inputs.",
      "Prepares a cleanup list for the owner.",
    ],
    dataSources: ["Territories", "Onboarding checklists", "Tasks", "Launch notes"],
    guardrails: ["Checklist-based", "Does not approve launch alone", "Escalates critical blockers"],
    canDo: ["Audit readiness", "Find blockers", "Create launch prep summaries"],
    cannotDo: ["Approve openings", "Override leadership", "Ignore missing checklist items"],
    costPerRunEstimate: "$0.002/run est.",
    trustLevel: "read-only",
    supportsManualRun: false,
    supportsConversation: true,
    portrait: {
      initials: "SR",
      accent: "from-orange-500 to-lime-400",
      background: "from-orange-50 via-white to-lime-50",
      jacket: "bg-orange-800",
      expression: "Prepared",
    },
  },
  {
    name: "document-review",
    label: "Document Review",
    roleTitle: "Document Intelligence Agent",
    category: "operations",
    status: "planned",
    trigger: "Future file upload, document intake, and review workflows",
    description: "Reads uploaded documents and turns them into summaries, risks, missing fields, and action items.",
    mission: "Make paperwork usable instead of letting important details sit inside PDFs and spreadsheets.",
    uses: ["Summarizes documents", "Extracts action items", "Flags missing or risky fields"],
    howItWorks: [
      "Accepts approved uploaded files.",
      "Extracts text and structured fields.",
      "Summarizes key facts, risks, and next steps.",
      "Routes uncertain items to human review.",
    ],
    dataSources: ["Uploaded documents", "Contacts", "Journeys", "Knowledge base"],
    guardrails: ["Human review for important decisions", "Does not sign or submit documents", "Shows source context"],
    canDo: ["Summarize files", "Extract key details", "Create review tasks"],
    cannotDo: ["Sign documents", "Give legal advice", "Treat extraction as final truth"],
    costPerRunEstimate: "$0.002/run est.",
    trustLevel: "drafts-only",
    supportsManualRun: false,
    supportsConversation: true,
    portrait: {
      initials: "DR",
      accent: "from-stone-500 to-sky-400",
      background: "from-stone-50 via-white to-sky-50",
      jacket: "bg-stone-800",
      expression: "Careful",
    },
  },
  {
    name: "leadership-brief",
    label: "Leadership Brief",
    roleTitle: "Executive Summary Agent",
    category: "operations",
    status: "planned",
    trigger: "Future weekly leadership review and daily operating summary",
    description: "Summarizes pipeline health, blockers, agent activity, forecasts, and priority decisions for leadership.",
    mission: "Give leadership a clean operating read without digging through every page.",
    uses: ["Creates executive summaries", "Highlights blockers", "Frames weekly priorities"],
    howItWorks: [
      "Reads pipeline, agent, EOS, workflow, and marketing summaries.",
      "Separates facts, risks, and recommended decisions.",
      "Creates a concise leadership brief.",
      "Links back to the source areas that need attention.",
    ],
    dataSources: ["Pipeline", "Agent logs", "EOS", "Marketing", "Workflow health"],
    guardrails: ["Advisory summary only", "Links back to sources", "Escalates uncertainty"],
    canDo: ["Summarize the business", "Spot operating risks", "Recommend focus areas"],
    cannotDo: ["Make leadership decisions", "Hide bad news", "Replace source reports"],
    costPerRunEstimate: "$0.002/run est.",
    trustLevel: "read-only",
    supportsManualRun: false,
    supportsConversation: true,
    portrait: {
      initials: "LB",
      accent: "from-zinc-600 to-amber-400",
      background: "from-zinc-50 via-white to-amber-50",
      jacket: "bg-zinc-800",
      expression: "Clear",
    },
  },
];

export function getAgentByName(name: string): AgentRegistryEntry | undefined {
  return AGENT_REGISTRY.find((agent) => agent.name === name);
}
