export const dynamic = "force-dynamic";

/**
 * GET /api/journeys/:journeyId/brief
 *
 * Returns the stored journey brief (narrative + next actions).
 * Briefs are generated by the journey-brief-agent and stored in journey_briefs.
 */

import { NextRequest, NextResponse } from "next/server";
import { requireAuth } from "@/lib/auth";
import { createServerClient } from "@/lib/supabase/server";

export async function GET(request: NextRequest, { params }: { params: Promise<{ journeyId: string }> }) {
  const user = await requireAuth(request);
  if (user instanceof Response) return user;

  const { journeyId } = await params;
  const supabase = createServerClient();

  const { data } = await supabase
    .from("journey_briefs")
    .select("narrative, next_actions, stale, updated_at")
    .eq("journey_id", journeyId)
    .maybeSingle();

  if (!data) {
    return NextResponse.json({
      empty: true,
      narrative: "",
      next_actions: { primary: "Brief generating...", secondary: [] },
      stale: true,
    });
  }

  return NextResponse.json({
    empty: false,
    narrative: data.narrative,
    next_actions: data.next_actions,
    stale: data.stale,
    updated_at: data.updated_at,
  });
}
